include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: false

analyzer:
  errors:
    argument_type_not_assignable: ignore
    invalid_assignment: ignore
