analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: false
