// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/gateway/mock_iap_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:autonomy_flutter/gateway/iap_api.dart' as _i4;
import 'package:autonomy_flutter/model/account_v2_request.dart' as _i7;
import 'package:autonomy_flutter/model/backup_versions.dart' as _i3;
import 'package:autonomy_flutter/model/jwt.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJWT_0 extends _i1.SmartFake implements _i2.JWT {
  _FakeJWT_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupVersions_1 extends _i1.SmartFake
    implements _i3.BackupVersions {
  _FakeBackupVersions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnesignalIdentityHash_2 extends _i1.SmartFake
    implements _i2.OnesignalIdentityHash {
  _FakeOnesignalIdentityHash_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAPApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAPApi extends _i1.Mock implements _i4.IAPApi {
  MockIAPApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.JWT> auth(Map<String, dynamic>? body) => (super.noSuchMethod(
        Invocation.method(
          #auth,
          [body],
        ),
        returnValue: _i5.Future<_i2.JWT>.value(_FakeJWT_0(
          this,
          Invocation.method(
            #auth,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.JWT>);
  @override
  _i5.Future<dynamic> uploadProfile(
    String? requester,
    String? filename,
    String? appVersion,
    _i6.File? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfile,
          [
            requester,
            filename,
            appVersion,
            data,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.BackupVersions> getProfileVersions(
    String? requester,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileVersions,
          [
            requester,
            filename,
          ],
        ),
        returnValue: _i5.Future<_i3.BackupVersions>.value(_FakeBackupVersions_1(
          this,
          Invocation.method(
            #getProfileVersions,
            [
              requester,
              filename,
            ],
          ),
        )),
      ) as _i5.Future<_i3.BackupVersions>);
  @override
  _i5.Future<dynamic> getProfileData(
    String? requester,
    String? filename,
    String? version,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [
            requester,
            filename,
            version,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteAllProfiles(String? requester) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllProfiles,
          [requester],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i2.OnesignalIdentityHash> generateIdentityHash(
          Map<String, String>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIdentityHash,
          [body],
        ),
        returnValue: _i5.Future<_i2.OnesignalIdentityHash>.value(
            _FakeOnesignalIdentityHash_2(
          this,
          Invocation.method(
            #generateIdentityHash,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.OnesignalIdentityHash>);
  @override
  _i5.Future<dynamic> addIdentity(_i7.AccountV2Request? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIdentity,
          [body],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i2.JWT> authV2(_i7.AccountV2Request? body) => (super.noSuchMethod(
        Invocation.method(
          #authV2,
          [body],
        ),
        returnValue: _i5.Future<_i2.JWT>.value(_FakeJWT_0(
          this,
          Invocation.method(
            #authV2,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.JWT>);
  @override
  _i5.Future<dynamic> createAccount(_i7.AccountV2Request? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [body],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteIdentity(String? address) => (super.noSuchMethod(
        Invocation.method(
          #deleteIdentity,
          [address],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}
