// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/gateway/mock_iap_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:autonomy_flutter/gateway/iap_api.dart' as _i4;
import 'package:autonomy_flutter/model/announcement/announcement.dart' as _i6;
import 'package:autonomy_flutter/model/announcement/announcement_request.dart'
    as _i7;
import 'package:autonomy_flutter/model/jwt.dart' as _i2;
import 'package:autonomy_flutter/model/ok_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOnesignalIdentityHash_0 extends _i1.SmartFake
    implements _i2.OnesignalIdentityHash {
  _FakeOnesignalIdentityHash_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOkResponse_1 extends _i1.SmartFake implements _i3.OkResponse {
  _FakeOkResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAPApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAPApi extends _i1.Mock implements _i4.IAPApi {
  MockIAPApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> deleteAllProfiles(String? requester) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllProfiles,
          [requester],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i2.OnesignalIdentityHash> generateIdentityHash(
          Map<String, String>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIdentityHash,
          [body],
        ),
        returnValue: _i5.Future<_i2.OnesignalIdentityHash>.value(
            _FakeOnesignalIdentityHash_0(
          this,
          Invocation.method(
            #generateIdentityHash,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.OnesignalIdentityHash>);
  @override
  _i5.Future<List<_i6.Announcement>> getAnnouncements(
          _i7.AnnouncementRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnnouncements,
          [body],
        ),
        returnValue:
            _i5.Future<List<_i6.Announcement>>.value(<_i6.Announcement>[]),
      ) as _i5.Future<List<_i6.Announcement>>);
  @override
  _i5.Future<_i3.OkResponse> redeemGiftCode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #redeemGiftCode,
          [id],
        ),
        returnValue: _i5.Future<_i3.OkResponse>.value(_FakeOkResponse_1(
          this,
          Invocation.method(
            #redeemGiftCode,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.OkResponse>);
  @override
  _i5.Future<void> updateMetrics(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #updateMetrics,
          [deviceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> sendEvent(
    Map<String, dynamic>? metrics,
    String? deviceId,
    String? deviceName,
    String? deviceVendor,
    String? deviceModel,
    String? devicePlatform,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [
            metrics,
            deviceId,
            deviceName,
            deviceVendor,
            deviceModel,
            devicePlatform,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteMetrics(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMetrics,
          [deviceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> registerReferralCode(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerReferralCode,
          [body],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<dynamic> portalUrl() => (super.noSuchMethod(
        Invocation.method(
          #portalUrl,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> getCustomActiveSubscription() => (super.noSuchMethod(
        Invocation.method(
          #getCustomActiveSubscription,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}
