// Mocks generated by Mockito 5.4.2 from annotations
// in autonomy_flutter/test/generate_mock/gateway/mock_postcard_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:autonomy_flutter/gateway/postcard_api.dart' as _i4;
import 'package:autonomy_flutter/model/postcard_claim.dart' as _i2;
import 'package:autonomy_flutter/model/prompt.dart' as _i7;
import 'package:autonomy_flutter/screen/send_receive_postcard/receive_postcard_page.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClaimPostCardResponse_0 extends _i1.SmartFake
    implements _i2.ClaimPostCardResponse {
  _FakeClaimPostCardResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestPostcardResponse_1 extends _i1.SmartFake
    implements _i2.RequestPostcardResponse {
  _FakeRequestPostcardResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReceivePostcardResponse_2 extends _i1.SmartFake
    implements _i3.ReceivePostcardResponse {
  _FakeReceivePostcardResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLeaderboardResponse_3 extends _i1.SmartFake
    implements _i4.GetLeaderboardResponse {
  _FakeGetLeaderboardResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostcardApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostcardApi extends _i1.Mock implements _i4.PostcardApi {
  MockPostcardApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ClaimPostCardResponse> claim(_i2.ClaimPostCardRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #claim,
          [body],
        ),
        returnValue: _i5.Future<_i2.ClaimPostCardResponse>.value(
            _FakeClaimPostCardResponse_0(
          this,
          Invocation.method(
            #claim,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.ClaimPostCardResponse>);
  @override
  _i5.Future<_i2.RequestPostcardResponse> request(
          _i2.RequestPostcardRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [body],
        ),
        returnValue: _i5.Future<_i2.RequestPostcardResponse>.value(
            _FakeRequestPostcardResponse_1(
          this,
          Invocation.method(
            #request,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.RequestPostcardResponse>);
  @override
  _i5.Future<_i3.ReceivePostcardResponse> receive(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #receive,
          [body],
        ),
        returnValue: _i5.Future<_i3.ReceivePostcardResponse>.value(
            _FakeReceivePostcardResponse_2(
          this,
          Invocation.method(
            #receive,
            [body],
          ),
        )),
      ) as _i5.Future<_i3.ReceivePostcardResponse>);
  @override
  _i5.Future<dynamic> share(
    String? tokenId,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #share,
          [
            tokenId,
            body,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> claimShareCode(String? shareCode) => (super.noSuchMethod(
        Invocation.method(
          #claimShareCode,
          [shareCode],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<String> getMerchandiseEnable(String? tokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerchandiseEnable,
          [tokenId],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<dynamic> updatePostcard({
    required String? tokenId,
    required _i6.File? data,
    required _i6.File? metadata,
    required String? signature,
    required String? address,
    required String? publicKey,
    required int? counter,
    double? lat,
    double? lon,
    String? promptID,
    String? prompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePostcard,
          [],
          {
            #tokenId: tokenId,
            #data: data,
            #metadata: metadata,
            #signature: signature,
            #address: address,
            #publicKey: publicKey,
            #counter: counter,
            #lat: lat,
            #lon: lon,
            #promptID: promptID,
            #prompt: prompt,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i4.GetLeaderboardResponse> getLeaderboard(
    String? unit,
    int? size,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [
            unit,
            size,
            offset,
          ],
        ),
        returnValue: _i5.Future<_i4.GetLeaderboardResponse>.value(
            _FakeGetLeaderboardResponse_3(
          this,
          Invocation.method(
            #getLeaderboard,
            [
              unit,
              size,
              offset,
            ],
          ),
        )),
      ) as _i5.Future<_i4.GetLeaderboardResponse>);
  @override
  _i5.Future<List<_i7.Prompt>> getPrompts(String? tokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrompts,
          [tokenId],
        ),
        returnValue: _i5.Future<List<_i7.Prompt>>.value(<_i7.Prompt>[]),
      ) as _i5.Future<List<_i7.Prompt>>);
}
