// Mocks generated by Mockito 5.4.2 from annotations
// in autonomy_flutter/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i12;

import 'package:autonomy_flutter/database/entity/announcement_local.dart'
    as _i29;
import 'package:autonomy_flutter/database/entity/connection.dart' as _i7;
import 'package:autonomy_flutter/database/entity/persona.dart' as _i5;
import 'package:autonomy_flutter/database/entity/wallet_address.dart' as _i19;
import 'package:autonomy_flutter/gateway/iap_api.dart' as _i10;
import 'package:autonomy_flutter/model/backup_versions.dart' as _i3;
import 'package:autonomy_flutter/model/jwt.dart' as _i2;
import 'package:autonomy_flutter/model/network.dart' as _i23;
import 'package:autonomy_flutter/model/play_list_model.dart' as _i25;
import 'package:autonomy_flutter/model/sent_artwork.dart' as _i24;
import 'package:autonomy_flutter/model/shared_postcard.dart' as _i21;
import 'package:autonomy_flutter/screen/bloc/scan_wallet/scan_wallet_state.dart'
    as _i18;
import 'package:autonomy_flutter/screen/interactive_postcard/postcard_detail_page.dart'
    as _i27;
import 'package:autonomy_flutter/screen/interactive_postcard/stamp_preview.dart'
    as _i26;
import 'package:autonomy_flutter/service/account_service.dart' as _i13;
import 'package:autonomy_flutter/service/configuration_service.dart' as _i20;
import 'package:autonomy_flutter/service/mix_panel_client_service.dart' as _i28;
import 'package:autonomy_flutter/service/wallet_connect_dapp_service/wc_connected_session.dart'
    as _i15;
import 'package:autonomy_flutter/util/announcement_ext.dart' as _i9;
import 'package:autonomy_flutter/util/constants.dart' as _i16;
import 'package:autonomy_flutter/util/wallet_storage_ext.dart' as _i6;
import 'package:autonomy_flutter/util/wallet_utils.dart' as _i14;
import 'package:flutter/material.dart' as _i8;
import 'package:libauk_dart/libauk_dart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nft_collection/models/models.dart' as _i17;
import 'package:wallet_connect/wallet_connect.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJWT_0 extends _i1.SmartFake implements _i2.JWT {
  _FakeJWT_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupVersions_1 extends _i1.SmartFake
    implements _i3.BackupVersions {
  _FakeBackupVersions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnesignalIdentityHash_2 extends _i1.SmartFake
    implements _i2.OnesignalIdentityHash {
  _FakeOnesignalIdentityHash_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletStorage_3 extends _i1.SmartFake implements _i4.WalletStorage {
  _FakeWalletStorage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersona_4 extends _i1.SmartFake implements _i5.Persona {
  _FakePersona_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletIndex_5 extends _i1.SmartFake implements _i6.WalletIndex {
  _FakeWalletIndex_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnection_6 extends _i1.SmartFake implements _i7.Connection {
  _FakeConnection_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_7<T> extends _i1.SmartFake
    implements _i8.ValueNotifier<T> {
  _FakeValueNotifier_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShowAnouncementNotificationInfo_8 extends _i1.SmartFake
    implements _i9.ShowAnouncementNotificationInfo {
  _FakeShowAnouncementNotificationInfo_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAPApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAPApi extends _i1.Mock implements _i10.IAPApi {
  MockIAPApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.JWT> auth(Map<String, dynamic>? body) => (super.noSuchMethod(
        Invocation.method(
          #auth,
          [body],
        ),
        returnValue: _i11.Future<_i2.JWT>.value(_FakeJWT_0(
          this,
          Invocation.method(
            #auth,
            [body],
          ),
        )),
      ) as _i11.Future<_i2.JWT>);
  @override
  _i11.Future<dynamic> uploadProfile(
    String? requester,
    String? filename,
    String? appVersion,
    _i12.File? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfile,
          [
            requester,
            filename,
            appVersion,
            data,
          ],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<_i3.BackupVersions> getProfileVersions(
    String? requester,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileVersions,
          [
            requester,
            filename,
          ],
        ),
        returnValue:
            _i11.Future<_i3.BackupVersions>.value(_FakeBackupVersions_1(
          this,
          Invocation.method(
            #getProfileVersions,
            [
              requester,
              filename,
            ],
          ),
        )),
      ) as _i11.Future<_i3.BackupVersions>);
  @override
  _i11.Future<dynamic> getProfileData(
    String? requester,
    String? filename,
    String? version,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [
            requester,
            filename,
            version,
          ],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> deleteAllProfiles(String? requester) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllProfiles,
          [requester],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> deleteUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<_i2.OnesignalIdentityHash> generateIdentityHash(
          Map<String, String>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIdentityHash,
          [body],
        ),
        returnValue: _i11.Future<_i2.OnesignalIdentityHash>.value(
            _FakeOnesignalIdentityHash_2(
          this,
          Invocation.method(
            #generateIdentityHash,
            [body],
          ),
        )),
      ) as _i11.Future<_i2.OnesignalIdentityHash>);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i13.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i4.WalletStorage> getDefaultAccount() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultAccount,
          [],
        ),
        returnValue: _i11.Future<_i4.WalletStorage>.value(_FakeWalletStorage_3(
          this,
          Invocation.method(
            #getDefaultAccount,
            [],
          ),
        )),
      ) as _i11.Future<_i4.WalletStorage>);
  @override
  _i11.Future<_i5.Persona> getOrCreateDefaultPersona() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateDefaultPersona,
          [],
        ),
        returnValue: _i11.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #getOrCreateDefaultPersona,
            [],
          ),
        )),
      ) as _i11.Future<_i5.Persona>);
  @override
  _i11.Future<_i4.WalletStorage?> getCurrentDefaultAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentDefaultAccount,
          [],
        ),
        returnValue: _i11.Future<_i4.WalletStorage?>.value(),
      ) as _i11.Future<_i4.WalletStorage?>);
  @override
  _i11.Future<_i4.WalletStorage?> getAccount(String? did) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [did],
        ),
        returnValue: _i11.Future<_i4.WalletStorage?>.value(),
      ) as _i11.Future<_i4.WalletStorage?>);
  @override
  _i11.Future<_i6.WalletIndex> getAccountByAddress({
    required String? chain,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountByAddress,
          [],
          {
            #chain: chain,
            #address: address,
          },
        ),
        returnValue: _i11.Future<_i6.WalletIndex>.value(_FakeWalletIndex_5(
          this,
          Invocation.method(
            #getAccountByAddress,
            [],
            {
              #chain: chain,
              #address: address,
            },
          ),
        )),
      ) as _i11.Future<_i6.WalletIndex>);
  @override
  _i11.Future<dynamic> androidBackupKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidBackupKeys,
          [],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<bool?> isAndroidEndToEndEncryptionAvailable() =>
      (super.noSuchMethod(
        Invocation.method(
          #isAndroidEndToEndEncryptionAvailable,
          [],
        ),
        returnValue: _i11.Future<bool?>.value(),
      ) as _i11.Future<bool?>);
  @override
  _i11.Future<dynamic> androidRestoreKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidRestoreKeys,
          [],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<List<_i5.Persona>> getPersonas() => (super.noSuchMethod(
        Invocation.method(
          #getPersonas,
          [],
        ),
        returnValue: _i11.Future<List<_i5.Persona>>.value(<_i5.Persona>[]),
      ) as _i11.Future<List<_i5.Persona>>);
  @override
  _i11.Future<_i5.Persona> createPersona({
    String? name = r'',
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPersona,
          [],
          {
            #name: name,
            #isDefault: isDefault,
          },
        ),
        returnValue: _i11.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #createPersona,
            [],
            {
              #name: name,
              #isDefault: isDefault,
            },
          ),
        )),
      ) as _i11.Future<_i5.Persona>);
  @override
  _i11.Future<_i5.Persona> importPersona(
    String? words, {
    _i14.WalletType? walletType = _i14.WalletType.Autonomy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importPersona,
          [words],
          {#walletType: walletType},
        ),
        returnValue: _i11.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #importPersona,
            [words],
            {#walletType: walletType},
          ),
        )),
      ) as _i11.Future<_i5.Persona>);
  @override
  _i11.Future<_i5.Persona> namePersona(
    _i5.Persona? persona,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #namePersona,
          [
            persona,
            name,
          ],
        ),
        returnValue: _i11.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #namePersona,
            [
              persona,
              name,
            ],
          ),
        )),
      ) as _i11.Future<_i5.Persona>);
  @override
  _i11.Future<_i7.Connection> nameLinkedAccount(
    _i7.Connection? connection,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #nameLinkedAccount,
          [
            connection,
            name,
          ],
        ),
        returnValue: _i11.Future<_i7.Connection>.value(_FakeConnection_6(
          this,
          Invocation.method(
            #nameLinkedAccount,
            [
              connection,
              name,
            ],
          ),
        )),
      ) as _i11.Future<_i7.Connection>);
  @override
  _i11.Future<_i7.Connection> linkETHWallet(_i15.WCConnectedSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkETHWallet,
          [session],
        ),
        returnValue: _i11.Future<_i7.Connection>.value(_FakeConnection_6(
          this,
          Invocation.method(
            #linkETHWallet,
            [session],
          ),
        )),
      ) as _i11.Future<_i7.Connection>);
  @override
  _i11.Future<_i7.Connection> linkETHBrowserWallet(
    String? address,
    _i16.WalletApp? walletApp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkETHBrowserWallet,
          [
            address,
            walletApp,
          ],
        ),
        returnValue: _i11.Future<_i7.Connection>.value(_FakeConnection_6(
          this,
          Invocation.method(
            #linkETHBrowserWallet,
            [
              address,
              walletApp,
            ],
          ),
        )),
      ) as _i11.Future<_i7.Connection>);
  @override
  _i11.Future<_i7.Connection> linkManuallyAddress(
    String? address,
    _i16.CryptoType? cryptoType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkManuallyAddress,
          [
            address,
            cryptoType,
          ],
        ),
        returnValue: _i11.Future<_i7.Connection>.value(_FakeConnection_6(
          this,
          Invocation.method(
            #linkManuallyAddress,
            [
              address,
              cryptoType,
            ],
          ),
        )),
      ) as _i11.Future<_i7.Connection>);
  @override
  _i11.Future<bool> isLinkedIndexerTokenID(String? indexerTokenID) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLinkedIndexerTokenID,
          [indexerTokenID],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<dynamic> deletePersona(_i5.Persona? persona) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePersona,
          [persona],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> deleteLinkedAccount(_i7.Connection? connection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLinkedAccount,
          [connection],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> linkIndexerTokenID(String? indexerTokenID) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkIndexerTokenID,
          [indexerTokenID],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setHideLinkedAccountInGallery(
    String? address,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setHideAddressInGallery(
    List<String>? addresses,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideAddressInGallery,
          [
            addresses,
            isEnabled,
          ],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool isLinkedAccountHiddenInGallery(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [address],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<List<String>> getAllAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getAllAddresses,
          [],
        ),
        returnValue: _i11.Future<List<String>>.value(<String>[]),
      ) as _i11.Future<List<String>>);
  @override
  _i11.Future<List<_i17.AddressIndex>> getAllAddressIndexes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAddressIndexes,
          [],
        ),
        returnValue:
            _i11.Future<List<_i17.AddressIndex>>.value(<_i17.AddressIndex>[]),
      ) as _i11.Future<List<_i17.AddressIndex>>);
  @override
  _i11.Future<List<String>> getAddress(String? blockchain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddress,
          [blockchain],
        ),
        returnValue: _i11.Future<List<String>>.value(<String>[]),
      ) as _i11.Future<List<String>>);
  @override
  _i11.Future<List<_i17.AddressIndex>> getHiddenAddressIndexes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHiddenAddressIndexes,
          [],
        ),
        returnValue:
            _i11.Future<List<_i17.AddressIndex>>.value(<_i17.AddressIndex>[]),
      ) as _i11.Future<List<_i17.AddressIndex>>);
  @override
  _i11.Future<List<String>> getShowedAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getShowedAddresses,
          [],
        ),
        returnValue: _i11.Future<List<String>>.value(<String>[]),
      ) as _i11.Future<List<String>>);
  @override
  _i11.Future<String> authorizeToViewer() => (super.noSuchMethod(
        Invocation.method(
          #authorizeToViewer,
          [],
        ),
        returnValue: _i11.Future<String>.value(''),
      ) as _i11.Future<String>);
  @override
  _i11.Future<_i5.Persona> addAddressPersona(
    _i5.Persona? newPersona,
    List<_i18.AddressInfo>? addresses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAddressPersona,
          [
            newPersona,
            addresses,
          ],
        ),
        returnValue: _i11.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #addAddressPersona,
            [
              newPersona,
              addresses,
            ],
          ),
        )),
      ) as _i11.Future<_i5.Persona>);
  @override
  _i11.Future<void> deleteAddressPersona(
    _i5.Persona? persona,
    _i19.WalletAddress? walletAddress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAddressPersona,
          [
            persona,
            walletAddress,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<_i19.WalletAddress?> getAddressPersona(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressPersona,
          [address],
        ),
        returnValue: _i11.Future<_i19.WalletAddress?>.value(),
      ) as _i11.Future<_i19.WalletAddress?>);
  @override
  _i11.Future<void> updateAddressPersona(_i19.WalletAddress? walletAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddressPersona,
          [walletAddress],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> restoreIfNeeded({bool? isCreateNew = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreIfNeeded,
          [],
          {#isCreateNew: isCreateNew},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [ConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationService extends _i1.Mock
    implements _i20.ConfigurationService {
  MockConfigurationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ValueNotifier<bool> get showNotifTip => (super.noSuchMethod(
        Invocation.getter(#showNotifTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showNotifTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showProTip => (super.noSuchMethod(
        Invocation.getter(#showProTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showProTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showTvAppTip => (super.noSuchMethod(
        Invocation.getter(#showTvAppTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showTvAppTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showCreatePlaylistTip => (super.noSuchMethod(
        Invocation.getter(#showCreatePlaylistTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showCreatePlaylistTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showLinkOrImportTip => (super.noSuchMethod(
        Invocation.getter(#showLinkOrImportTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showLinkOrImportTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showBackupSettingTip => (super.noSuchMethod(
        Invocation.getter(#showBackupSettingTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showBackupSettingTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<bool> get showWhatNewAddressTip => (super.noSuchMethod(
        Invocation.getter(#showWhatNewAddressTip),
        returnValue: _FakeValueNotifier_7<bool>(
          this,
          Invocation.getter(#showWhatNewAddressTip),
        ),
      ) as _i8.ValueNotifier<bool>);
  @override
  _i8.ValueNotifier<List<_i21.SharedPostcard>>
      get expiredPostcardSharedLinkTip => (super.noSuchMethod(
            Invocation.getter(#expiredPostcardSharedLinkTip),
            returnValue: _FakeValueNotifier_7<List<_i21.SharedPostcard>>(
              this,
              Invocation.getter(#expiredPostcardSharedLinkTip),
            ),
          ) as _i8.ValueNotifier<List<_i21.SharedPostcard>>);
  @override
  _i11.Future<void> setAnnouncementLastPullTime(int? lastPullTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAnnouncementLastPullTime,
          [lastPullTime],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setOldUser() => (super.noSuchMethod(
        Invocation.method(
          #setOldUser,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool getIsOldUser() => (super.noSuchMethod(
        Invocation.method(
          #getIsOldUser,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setIAPReceipt(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPReceipt,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setIAPJWT(_i2.JWT? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPJWT,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setPremium(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setPremium,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isPremium() => (super.noSuchMethod(
        Invocation.method(
          #isPremium,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setTVConnectData(
    _i22.WCPeerMeta? peerMeta,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTVConnectData,
          [
            peerMeta,
            id,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> deleteTVConnectData() => (super.noSuchMethod(
        Invocation.method(
          #deleteTVConnectData,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setWCSessions(List<_i22.WCSessionStore>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWCSessions,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<_i22.WCSessionStore> getWCSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWCSessions,
          [],
        ),
        returnValue: <_i22.WCSessionStore>[],
      ) as List<_i22.WCSessionStore>);
  @override
  _i11.Future<void> setDevicePasscodeEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDevicePasscodeEnabled,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isDevicePasscodeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDevicePasscodeEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setNotificationEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationEnabled,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setAnalyticEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticEnabled,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setDoneOnboarding(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboarding,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isDoneOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setPendingSettings(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setPendingSettings,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool hasPendingSettings() => (super.noSuchMethod(
        Invocation.method(
          #hasPendingSettings,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool shouldShowSubscriptionHint() => (super.noSuchMethod(
        Invocation.method(
          #shouldShowSubscriptionHint,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setShouldShowSubscriptionHint(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShouldShowSubscriptionHint,
          [value],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setLastTimeAskForSubscription(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastTimeAskForSubscription,
          [date],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<void> setDoneOnboardingOnce(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingOnce,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isDoneOnboardingOnce() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboardingOnce,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setFullscreenIntroEnable(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFullscreenIntroEnable,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isFullscreenIntroEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isFullscreenIntroEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> readRemoveSupport(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #readRemoveSupport,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isReadRemoveSupport() => (super.noSuchMethod(
        Invocation.method(
          #isReadRemoveSupport,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setHideLinkedAccountInGallery(
    List<String>? address,
    bool? isEnabled, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
          {#override: override},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<String> getLinkedAccountsHiddenInGallery() => (super.noSuchMethod(
        Invocation.method(
          #getLinkedAccountsHiddenInGallery,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  bool isLinkedAccountHiddenInGallery(String? value) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [value],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<String> getTempStorageHiddenTokenIDs({_i23.Network? network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTempStorageHiddenTokenIDs,
          [],
          {#network: network},
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i11.Future<dynamic> updateTempStorageHiddenTokenIDs(
    List<String>? tokenIDs,
    bool? isAdd, {
    _i23.Network? network,
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTempStorageHiddenTokenIDs,
          [
            tokenIDs,
            isAdd,
          ],
          {
            #network: network,
            #override: override,
          },
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  List<_i24.SentArtwork> getRecentlySentToken() => (super.noSuchMethod(
        Invocation.method(
          #getRecentlySentToken,
          [],
        ),
        returnValue: <_i24.SentArtwork>[],
      ) as List<_i24.SentArtwork>);
  @override
  _i11.Future<dynamic> updateRecentlySentToken(
    List<_i24.SentArtwork>? sentArtwork, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecentlySentToken,
          [sentArtwork],
          {#override: override},
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<void> setWCDappSession(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setWCDappSession,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setWCDappAccounts(List<String>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWCDappAccounts,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<bool> setLatestRefreshTokens(DateTime? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLatestRefreshTokens,
          [value],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  _i11.Future<void> setReadReleaseNotesInVersion(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadReleaseNotesInVersion,
          [version],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setPreviousBuildNumber(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreviousBuildNumber,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<_i25.PlayListModel> getPlayList() => (super.noSuchMethod(
        Invocation.method(
          #getPlayList,
          [],
        ),
        returnValue: <_i25.PlayListModel>[],
      ) as List<_i25.PlayListModel>);
  @override
  _i11.Future<void> setPlayList(
    List<_i25.PlayListModel>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlayList,
          [value],
          {#override: override},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removePlayList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removePlayList,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<String> getFinishedSurveys() => (super.noSuchMethod(
        Invocation.method(
          #getFinishedSurveys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i11.Future<void> setFinishedSurvey(List<String>? surveyNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFinishedSurvey,
          [surveyNames],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<String> getAccountHMACSecret() => (super.noSuchMethod(
        Invocation.method(
          #getAccountHMACSecret,
          [],
        ),
        returnValue: _i11.Future<String>.value(''),
      ) as _i11.Future<String>);
  @override
  bool isFinishedFeedOnBoarding() => (super.noSuchMethod(
        Invocation.method(
          #isFinishedFeedOnBoarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setFinishedFeedOnBoarding(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFinishedFeedOnBoarding,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setLastRemindReviewDate(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastRemindReviewDate,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setCountOpenApp(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setCountOpenApp,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setLastTimeOpenFeed(int? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #setLastTimeOpenFeed,
          [timestamp],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  int getLastTimeOpenFeed() => (super.noSuchMethod(
        Invocation.method(
          #getLastTimeOpenFeed,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  _i11.Future<void> setHasFeed(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setHasFeed,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool hasFeed() => (super.noSuchMethod(
        Invocation.method(
          #hasFeed,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setLastTimeOpenEditorial(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastTimeOpenEditorial,
          [time],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool isDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #isDemoArtworksMode,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<bool> toggleDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDemoArtworksMode,
          [],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
  @override
  bool showTokenDebugInfo() => (super.noSuchMethod(
        Invocation.method(
          #showTokenDebugInfo,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setShowTokenDebugInfo(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTokenDebugInfo,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool isLastestVersion() => (super.noSuchMethod(
        Invocation.method(
          #isLastestVersion,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setLastestVersion(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setLastestVersion,
          [value],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setDoneOnboardingTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingTime,
          [time],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setSubscriptionTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionTime,
          [time],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setAlreadyShowNotifTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowNotifTip,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setAlreadyShowProTip(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowProTip,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setAlreadyShowTvAppTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowTvAppTip,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setAlreadyShowCreatePlaylistTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowCreatePlaylistTip,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setAlreadyShowLinkOrImportTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowLinkOrImportTip,
          [show],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool getAlreadyShowNotifTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowNotifTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowProTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowProTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowTvAppTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowTvAppTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowCreatePlaylistTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowCreatePlaylistTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowLinkOrImportTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowLinkOrImportTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setShowBackupSettingTip(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowBackupSettingTip,
          [time],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool getShowWhatNewAddressTip(int? currentVersion) => (super.noSuchMethod(
        Invocation.method(
          #getShowWhatNewAddressTip,
          [currentVersion],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<dynamic> setShowWhatNewAddressTipRead(int? currentVersion) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowWhatNewAddressTipRead,
          [currentVersion],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> setSentTezosArtworkMetric(int? hashedAddresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSentTezosArtworkMetric,
          [hashedAddresses],
        ),
        returnValue: _i11.Future<dynamic>.value(),
      ) as _i11.Future<dynamic>);
  @override
  bool allowContribution() => (super.noSuchMethod(
        Invocation.method(
          #allowContribution,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setAllowContribution(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAllowContribution,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<_i21.SharedPostcard> getSharedPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getSharedPostcard,
          [],
        ),
        returnValue: <_i21.SharedPostcard>[],
      ) as List<_i21.SharedPostcard>);
  @override
  _i11.Future<void> updateSharedPostcard(
    List<_i21.SharedPostcard>? sharedPostcards, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedPostcard,
          [sharedPostcards],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeSharedPostcardWhere(
          bool Function(_i21.SharedPostcard)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSharedPostcardWhere,
          [test],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<String> getListPostcardMint() => (super.noSuchMethod(
        Invocation.method(
          #getListPostcardMint,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i11.Future<void> setListPostcardMint(
    List<String>? tokenID, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardMint,
          [tokenID],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<_i26.StampingPostcard> getStampingPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getStampingPostcard,
          [],
        ),
        returnValue: <_i26.StampingPostcard>[],
      ) as List<_i26.StampingPostcard>);
  @override
  _i11.Future<void> updateStampingPostcard(
    List<_i26.StampingPostcard>? values, {
    bool? override = false,
    bool? isRemove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStampingPostcard,
          [values],
          {
            #override: override,
            #isRemove: isRemove,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeExpiredStampingPostcard() => (super.noSuchMethod(
        Invocation.method(
          #removeExpiredStampingPostcard,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setAutoShowPostcard(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoShowPostcard,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  bool isAutoShowPostcard() => (super.noSuchMethod(
        Invocation.method(
          #isAutoShowPostcard,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<_i27.PostcardIdentity> getListPostcardAlreadyShowYouDidIt() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListPostcardAlreadyShowYouDidIt,
          [],
        ),
        returnValue: <_i27.PostcardIdentity>[],
      ) as List<_i27.PostcardIdentity>);
  @override
  _i11.Future<void> setListPostcardAlreadyShowYouDidIt(
    List<_i27.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardAlreadyShowYouDidIt,
          [value],
          {#override: override},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setMixpanelConfig(_i28.MixpanelConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMixpanelConfig,
          [config],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> setAlreadyShowPostcardUpdates(
    List<_i27.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowPostcardUpdates,
          [value],
          {#override: override},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  List<_i27.PostcardIdentity> getAlreadyShowPostcardUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowPostcardUpdates,
          [],
        ),
        returnValue: <_i27.PostcardIdentity>[],
      ) as List<_i27.PostcardIdentity>);
  @override
  String getVersionInfo() => (super.noSuchMethod(
        Invocation.method(
          #getVersionInfo,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i11.Future<void> setVersionInfo(String? version) => (super.noSuchMethod(
        Invocation.method(
          #setVersionInfo,
          [version],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> updateShowAnouncementNotificationInfo(
          _i29.AnnouncementLocal? announcement) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShowAnouncementNotificationInfo,
          [announcement],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i9.ShowAnouncementNotificationInfo getShowAnouncementNotificationInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getShowAnouncementNotificationInfo,
          [],
        ),
        returnValue: _FakeShowAnouncementNotificationInfo_8(
          this,
          Invocation.method(
            #getShowAnouncementNotificationInfo,
            [],
          ),
        ),
      ) as _i9.ShowAnouncementNotificationInfo);
  @override
  bool getAlreadyClaimedAirdrop(String? seriesId) => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyClaimedAirdrop,
          [seriesId],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> setAlreadyClaimedAirdrop(
    String? seriesId,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyClaimedAirdrop,
          [
            seriesId,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
