// Mocks generated by Mockito 5.3.2 from annotations
// in autonomy_flutter/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i9;

import 'package:autonomy_flutter/database/entity/connection.dart' as _i6;
import 'package:autonomy_flutter/database/entity/persona.dart' as _i5;
import 'package:autonomy_flutter/gateway/iap_api.dart' as _i7;
import 'package:autonomy_flutter/model/backup_versions.dart' as _i3;
import 'package:autonomy_flutter/model/jwt.dart' as _i2;
import 'package:autonomy_flutter/model/network.dart' as _i15;
import 'package:autonomy_flutter/model/play_list_model.dart' as _i17;
import 'package:autonomy_flutter/model/sent_artwork.dart' as _i16;
import 'package:autonomy_flutter/service/account_service.dart' as _i10;
import 'package:autonomy_flutter/service/configuration_service.dart' as _i13;
import 'package:autonomy_flutter/service/wallet_connect_dapp_service/wc_connected_session.dart'
    as _i11;
import 'package:autonomy_flutter/util/constants.dart' as _i12;
import 'package:libauk_dart/libauk_dart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wallet_connect/wallet_connect.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJWT_0 extends _i1.SmartFake implements _i2.JWT {
  _FakeJWT_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupVersions_1 extends _i1.SmartFake
    implements _i3.BackupVersions {
  _FakeBackupVersions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnesignalIdentityHash_2 extends _i1.SmartFake
    implements _i2.OnesignalIdentityHash {
  _FakeOnesignalIdentityHash_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletStorage_3 extends _i1.SmartFake implements _i4.WalletStorage {
  _FakeWalletStorage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersona_4 extends _i1.SmartFake implements _i5.Persona {
  _FakePersona_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnection_5 extends _i1.SmartFake implements _i6.Connection {
  _FakeConnection_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAPApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAPApi extends _i1.Mock implements _i7.IAPApi {
  MockIAPApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.JWT> auth(Map<String, dynamic>? body) => (super.noSuchMethod(
        Invocation.method(
          #auth,
          [body],
        ),
        returnValue: _i8.Future<_i2.JWT>.value(_FakeJWT_0(
          this,
          Invocation.method(
            #auth,
            [body],
          ),
        )),
      ) as _i8.Future<_i2.JWT>);
  @override
  _i8.Future<dynamic> uploadProfile(
    String? requester,
    String? filename,
    String? appVersion,
    _i9.File? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfile,
          [
            requester,
            filename,
            appVersion,
            data,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<_i3.BackupVersions> getProfileVersions(
    String? requester,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileVersions,
          [
            requester,
            filename,
          ],
        ),
        returnValue: _i8.Future<_i3.BackupVersions>.value(_FakeBackupVersions_1(
          this,
          Invocation.method(
            #getProfileVersions,
            [
              requester,
              filename,
            ],
          ),
        )),
      ) as _i8.Future<_i3.BackupVersions>);
  @override
  _i8.Future<dynamic> getProfileData(
    String? requester,
    String? filename,
    String? version,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [
            requester,
            filename,
            version,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> deleteAllProfiles(String? requester) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllProfiles,
          [requester],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> deleteUserData() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<_i2.OnesignalIdentityHash> generateIdentityHash(
          Map<String, String>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIdentityHash,
          [body],
        ),
        returnValue: _i8.Future<_i2.OnesignalIdentityHash>.value(
            _FakeOnesignalIdentityHash_2(
          this,
          Invocation.method(
            #generateIdentityHash,
            [body],
          ),
        )),
      ) as _i8.Future<_i2.OnesignalIdentityHash>);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i10.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.WalletStorage> getDefaultAccount() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultAccount,
          [],
        ),
        returnValue: _i8.Future<_i4.WalletStorage>.value(_FakeWalletStorage_3(
          this,
          Invocation.method(
            #getDefaultAccount,
            [],
          ),
        )),
      ) as _i8.Future<_i4.WalletStorage>);
  @override
  _i8.Future<_i4.WalletStorage?> getCurrentDefaultAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentDefaultAccount,
          [],
        ),
        returnValue: _i8.Future<_i4.WalletStorage?>.value(),
      ) as _i8.Future<_i4.WalletStorage?>);
  @override
  _i8.Future<dynamic> androidBackupKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidBackupKeys,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<bool?> isAndroidEndToEndEncryptionAvailable() =>
      (super.noSuchMethod(
        Invocation.method(
          #isAndroidEndToEndEncryptionAvailable,
          [],
        ),
        returnValue: _i8.Future<bool?>.value(),
      ) as _i8.Future<bool?>);
  @override
  _i8.Future<dynamic> androidRestoreKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidRestoreKeys,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<List<_i5.Persona>> getPersonas() => (super.noSuchMethod(
        Invocation.method(
          #getPersonas,
          [],
        ),
        returnValue: _i8.Future<List<_i5.Persona>>.value(<_i5.Persona>[]),
      ) as _i8.Future<List<_i5.Persona>>);
  @override
  _i8.Future<_i5.Persona> createPersona({String? name = r''}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPersona,
          [],
          {#name: name},
        ),
        returnValue: _i8.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #createPersona,
            [],
            {#name: name},
          ),
        )),
      ) as _i8.Future<_i5.Persona>);
  @override
  _i8.Future<_i5.Persona> importPersona(String? words) => (super.noSuchMethod(
        Invocation.method(
          #importPersona,
          [words],
        ),
        returnValue: _i8.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #importPersona,
            [words],
          ),
        )),
      ) as _i8.Future<_i5.Persona>);
  @override
  _i8.Future<_i5.Persona> namePersona(
    _i5.Persona? persona,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #namePersona,
          [
            persona,
            name,
          ],
        ),
        returnValue: _i8.Future<_i5.Persona>.value(_FakePersona_4(
          this,
          Invocation.method(
            #namePersona,
            [
              persona,
              name,
            ],
          ),
        )),
      ) as _i8.Future<_i5.Persona>);
  @override
  _i8.Future<_i6.Connection> nameLinkedAccount(
    _i6.Connection? connection,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #nameLinkedAccount,
          [
            connection,
            name,
          ],
        ),
        returnValue: _i8.Future<_i6.Connection>.value(_FakeConnection_5(
          this,
          Invocation.method(
            #nameLinkedAccount,
            [
              connection,
              name,
            ],
          ),
        )),
      ) as _i8.Future<_i6.Connection>);
  @override
  _i8.Future<_i6.Connection> linkETHWallet(_i11.WCConnectedSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkETHWallet,
          [session],
        ),
        returnValue: _i8.Future<_i6.Connection>.value(_FakeConnection_5(
          this,
          Invocation.method(
            #linkETHWallet,
            [session],
          ),
        )),
      ) as _i8.Future<_i6.Connection>);
  @override
  _i8.Future<_i6.Connection> linkETHBrowserWallet(
    String? address,
    _i12.WalletApp? walletApp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkETHBrowserWallet,
          [
            address,
            walletApp,
          ],
        ),
        returnValue: _i8.Future<_i6.Connection>.value(_FakeConnection_5(
          this,
          Invocation.method(
            #linkETHBrowserWallet,
            [
              address,
              walletApp,
            ],
          ),
        )),
      ) as _i8.Future<_i6.Connection>);
  @override
  _i8.Future<dynamic> linkManuallyAddress(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkManuallyAddress,
          [address],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<bool> isLinkedIndexerTokenID(String? indexerTokenID) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLinkedIndexerTokenID,
          [indexerTokenID],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
  @override
  _i8.Future<dynamic> deletePersona(_i5.Persona? persona) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePersona,
          [persona],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> deleteLinkedAccount(_i6.Connection? connection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLinkedAccount,
          [connection],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> linkIndexerTokenID(String? indexerTokenID) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkIndexerTokenID,
          [indexerTokenID],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> setHidePersonaInGallery(
    String? personaUUID,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHidePersonaInGallery,
          [
            personaUUID,
            isEnabled,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> setHideLinkedAccountInGallery(
    String? address,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  bool isPersonaHiddenInGallery(String? personaUUID) => (super.noSuchMethod(
        Invocation.method(
          #isPersonaHiddenInGallery,
          [personaUUID],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isLinkedAccountHiddenInGallery(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [address],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<List<String>> getAllAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getAllAddresses,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
  @override
  _i8.Future<List<String>> getAddress(String? blockchain) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddress,
          [blockchain],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
  @override
  _i8.Future<List<String>> getHiddenAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getHiddenAddresses,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
  @override
  _i8.Future<List<String>> getShowedAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getShowedAddresses,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
  @override
  _i8.Future<String> authorizeToViewer() => (super.noSuchMethod(
        Invocation.method(
          #authorizeToViewer,
          [],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
}

/// A class which mocks [ConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationService extends _i1.Mock
    implements _i13.ConfigurationService {
  MockConfigurationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> setIAPReceipt(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPReceipt,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setIAPJWT(_i2.JWT? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPJWT,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setTVConnectData(
    _i14.WCPeerMeta? peerMeta,
    int? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTVConnectData,
          [
            peerMeta,
            id,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> deleteTVConnectData() => (super.noSuchMethod(
        Invocation.method(
          #deleteTVConnectData,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setWCSessions(List<_i14.WCSessionStore>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWCSessions,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  List<_i14.WCSessionStore> getWCSessions() => (super.noSuchMethod(
        Invocation.method(
          #getWCSessions,
          [],
        ),
        returnValue: <_i14.WCSessionStore>[],
      ) as List<_i14.WCSessionStore>);
  @override
  _i8.Future<void> setDevicePasscodeEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDevicePasscodeEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isDevicePasscodeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDevicePasscodeEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setNotificationEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setAnalyticEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setDoneOnboarding(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboarding,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isDoneOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setPendingSettings(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setPendingSettings,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool hasPendingSettings() => (super.noSuchMethod(
        Invocation.method(
          #hasPendingSettings,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool shouldShowSubscriptionHint() => (super.noSuchMethod(
        Invocation.method(
          #shouldShowSubscriptionHint,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<dynamic> setShouldShowSubscriptionHint(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShouldShowSubscriptionHint,
          [value],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> setLastTimeAskForSubscription(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastTimeAskForSubscription,
          [date],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<void> setDoneOnboardingOnce(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingOnce,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isDoneOnboardingOnce() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboardingOnce,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setFullscreenIntroEnable(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setFullscreenIntroEnable,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isFullscreenIntroEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isFullscreenIntroEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setHidePersonaInGallery(
    List<String>? personaUUIDs,
    bool? isEnabled, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHidePersonaInGallery,
          [
            personaUUIDs,
            isEnabled,
          ],
          {#override: override},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  List<String> getPersonaUUIDsHiddenInGallery() => (super.noSuchMethod(
        Invocation.method(
          #getPersonaUUIDsHiddenInGallery,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  bool isPersonaHiddenInGallery(String? value) => (super.noSuchMethod(
        Invocation.method(
          #isPersonaHiddenInGallery,
          [value],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setHideLinkedAccountInGallery(
    List<String>? address,
    bool? isEnabled, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
          {#override: override},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  List<String> getLinkedAccountsHiddenInGallery() => (super.noSuchMethod(
        Invocation.method(
          #getLinkedAccountsHiddenInGallery,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  bool isLinkedAccountHiddenInGallery(String? value) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [value],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<String> getTempStorageHiddenTokenIDs({_i15.Network? network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTempStorageHiddenTokenIDs,
          [],
          {#network: network},
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i8.Future<dynamic> updateTempStorageHiddenTokenIDs(
    List<String>? tokenIDs,
    bool? isAdd, {
    _i15.Network? network,
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTempStorageHiddenTokenIDs,
          [
            tokenIDs,
            isAdd,
          ],
          {
            #network: network,
            #override: override,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  List<_i16.SentArtwork> getRecentlySentToken() => (super.noSuchMethod(
        Invocation.method(
          #getRecentlySentToken,
          [],
        ),
        returnValue: <_i16.SentArtwork>[],
      ) as List<_i16.SentArtwork>);
  @override
  _i8.Future<dynamic> updateRecentlySentToken(
    List<_i16.SentArtwork>? sentArtwork, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecentlySentToken,
          [sentArtwork],
          {#override: override},
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<void> setWCDappSession(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setWCDappSession,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setWCDappAccounts(List<String>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWCDappAccounts,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<bool> setLatestRefreshTokens(DateTime? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLatestRefreshTokens,
          [value],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
  @override
  _i8.Future<void> setReadReleaseNotesInVersion(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadReleaseNotesInVersion,
          [version],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setPreviousBuildNumber(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setPreviousBuildNumber,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setPlayList(
    List<_i17.PlayListModel>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlayList,
          [value],
          {#override: override},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  List<String> getFinishedSurveys() => (super.noSuchMethod(
        Invocation.method(
          #getFinishedSurveys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i8.Future<void> setFinishedSurvey(List<String>? surveyNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFinishedSurvey,
          [surveyNames],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setImmediateInfoViewEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setImmediateInfoViewEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  bool isImmediateInfoViewEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isImmediateInfoViewEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<String> getAccountHMACSecret() => (super.noSuchMethod(
        Invocation.method(
          #getAccountHMACSecret,
          [],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  bool isFinishedFeedOnBoarding() => (super.noSuchMethod(
        Invocation.method(
          #isFinishedFeedOnBoarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<void> setFinishedFeedOnBoarding(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFinishedFeedOnBoarding,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setLastRemindReviewDate(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastRemindReviewDate,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setCountOpenApp(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setCountOpenApp,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> setLastTimeOpenFeed(int? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #setLastTimeOpenFeed,
          [timestamp],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  int getLastTimeOpenFeed() => (super.noSuchMethod(
        Invocation.method(
          #getLastTimeOpenFeed,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  bool isDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #isDemoArtworksMode,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<bool> toggleDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDemoArtworksMode,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
  @override
  bool showTokenDebugInfo() => (super.noSuchMethod(
        Invocation.method(
          #showTokenDebugInfo,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i8.Future<dynamic> setShowTokenDebugInfo(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTokenDebugInfo,
          [show],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<dynamic> setSentTezosArtworkMetric(int? hashedAddresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSentTezosArtworkMetric,
          [hashedAddresses],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
  @override
  _i8.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
