// Mocks generated by Mockito 5.4.2 from annotations
// in autonomy_flutter/test/services/postcard_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:io' as _i16;
import 'dart:typed_data' as _i19;

import 'package:autonomy_flutter/database/entity/announcement_local.dart'
    as _i32;
import 'package:autonomy_flutter/database/entity/connection.dart' as _i13;
import 'package:autonomy_flutter/database/entity/persona.dart' as _i11;
import 'package:autonomy_flutter/database/entity/wallet_address.dart' as _i38;
import 'package:autonomy_flutter/gateway/postcard_api.dart' as _i4;
import 'package:autonomy_flutter/model/jwt.dart' as _i25;
import 'package:autonomy_flutter/model/network.dart' as _i26;
import 'package:autonomy_flutter/model/pair.dart' as _i43;
import 'package:autonomy_flutter/model/play_list_model.dart' as _i28;
import 'package:autonomy_flutter/model/postcard_claim.dart' as _i2;
import 'package:autonomy_flutter/model/prompt.dart' as _i17;
import 'package:autonomy_flutter/model/sent_artwork.dart' as _i27;
import 'package:autonomy_flutter/model/shared_postcard.dart' as _i29;
import 'package:autonomy_flutter/screen/bloc/scan_wallet/scan_wallet_state.dart'
    as _i37;
import 'package:autonomy_flutter/screen/chat/chat_thread_page.dart' as _i8;
import 'package:autonomy_flutter/screen/interactive_postcard/postcard_detail_page.dart'
    as _i31;
import 'package:autonomy_flutter/screen/interactive_postcard/stamp_preview.dart'
    as _i30;
import 'package:autonomy_flutter/screen/send_receive_postcard/receive_postcard_page.dart'
    as _i3;
import 'package:autonomy_flutter/service/account_service.dart' as _i33;
import 'package:autonomy_flutter/service/chat_service.dart' as _i42;
import 'package:autonomy_flutter/service/configuration_service.dart' as _i24;
import 'package:autonomy_flutter/service/metric_client_service.dart' as _i41;
import 'package:autonomy_flutter/service/mix_panel_client_service.dart' as _i14;
import 'package:autonomy_flutter/service/tezos_service.dart' as _i18;
import 'package:autonomy_flutter/util/announcement_ext.dart' as _i9;
import 'package:autonomy_flutter/util/constants.dart' as _i35;
import 'package:autonomy_flutter/util/wallet_storage_ext.dart' as _i12;
import 'package:autonomy_flutter/util/wallet_utils.dart' as _i34;
import 'package:flutter/material.dart' as _i7;
import 'package:libauk_dart/libauk_dart.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nft_collection/graphql/model/get_list_tokens.dart' as _i22;
import 'package:nft_collection/graphql/model/identity.dart' as _i23;
import 'package:nft_collection/models/asset_token.dart' as _i21;
import 'package:nft_collection/models/identity.dart' as _i6;
import 'package:nft_collection/models/models.dart' as _i36;
import 'package:nft_collection/models/pending_tx_params.dart' as _i40;
import 'package:nft_collection/services/indexer_service.dart' as _i20;
import 'package:nft_collection/services/tokens_service.dart' as _i39;
import 'package:tezart/tezart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClaimPostCardResponse_0 extends _i1.SmartFake
    implements _i2.ClaimPostCardResponse {
  _FakeClaimPostCardResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestPostcardResponse_1 extends _i1.SmartFake
    implements _i2.RequestPostcardResponse {
  _FakeRequestPostcardResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReceivePostcardResponse_2 extends _i1.SmartFake
    implements _i3.ReceivePostcardResponse {
  _FakeReceivePostcardResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLeaderboardResponse_3 extends _i1.SmartFake
    implements _i4.GetLeaderboardResponse {
  _FakeGetLeaderboardResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOperation_4 extends _i1.SmartFake implements _i5.Operation {
  _FakeOperation_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockchainIdentity_5 extends _i1.SmartFake
    implements _i6.BlockchainIdentity {
  _FakeBlockchainIdentity_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_6<T> extends _i1.SmartFake
    implements _i7.ValueNotifier<T> {
  _FakeValueNotifier_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostcardChatConfig_7 extends _i1.SmartFake
    implements _i8.PostcardChatConfig {
  _FakePostcardChatConfig_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShowAnouncementNotificationInfo_8 extends _i1.SmartFake
    implements _i9.ShowAnouncementNotificationInfo {
  _FakeShowAnouncementNotificationInfo_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletStorage_9 extends _i1.SmartFake implements _i10.WalletStorage {
  _FakeWalletStorage_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersona_10 extends _i1.SmartFake implements _i11.Persona {
  _FakePersona_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletIndex_11 extends _i1.SmartFake implements _i12.WalletIndex {
  _FakeWalletIndex_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnection_12 extends _i1.SmartFake implements _i13.Connection {
  _FakeConnection_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMixPanelClientService_13 extends _i1.SmartFake
    implements _i14.MixPanelClientService {
  _FakeMixPanelClientService_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostcardApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostcardApi extends _i1.Mock implements _i4.PostcardApi {
  MockPostcardApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i2.ClaimPostCardResponse> claim(
          _i2.ClaimPostCardRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #claim,
          [body],
        ),
        returnValue: _i15.Future<_i2.ClaimPostCardResponse>.value(
            _FakeClaimPostCardResponse_0(
          this,
          Invocation.method(
            #claim,
            [body],
          ),
        )),
      ) as _i15.Future<_i2.ClaimPostCardResponse>);
  @override
  _i15.Future<_i2.RequestPostcardResponse> request(
          _i2.RequestPostcardRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [body],
        ),
        returnValue: _i15.Future<_i2.RequestPostcardResponse>.value(
            _FakeRequestPostcardResponse_1(
          this,
          Invocation.method(
            #request,
            [body],
          ),
        )),
      ) as _i15.Future<_i2.RequestPostcardResponse>);
  @override
  _i15.Future<_i3.ReceivePostcardResponse> receive(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #receive,
          [body],
        ),
        returnValue: _i15.Future<_i3.ReceivePostcardResponse>.value(
            _FakeReceivePostcardResponse_2(
          this,
          Invocation.method(
            #receive,
            [body],
          ),
        )),
      ) as _i15.Future<_i3.ReceivePostcardResponse>);
  @override
  _i15.Future<dynamic> share(
    String? tokenId,
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #share,
          [
            tokenId,
            body,
          ],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> claimShareCode(String? shareCode) => (super.noSuchMethod(
        Invocation.method(
          #claimShareCode,
          [shareCode],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> updatePostcard({
    required String? tokenId,
    required _i16.File? data,
    required _i16.File? metadata,
    required String? signature,
    required String? address,
    required String? publicKey,
    required int? counter,
    double? lat,
    double? lon,
    String? promptID,
    String? prompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePostcard,
          [],
          {
            #tokenId: tokenId,
            #data: data,
            #metadata: metadata,
            #signature: signature,
            #address: address,
            #publicKey: publicKey,
            #counter: counter,
            #lat: lat,
            #lon: lon,
            #promptID: promptID,
            #prompt: prompt,
          },
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<_i4.GetLeaderboardResponse> getLeaderboard(
    String? unit,
    int? size,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [
            unit,
            size,
            offset,
          ],
        ),
        returnValue: _i15.Future<_i4.GetLeaderboardResponse>.value(
            _FakeGetLeaderboardResponse_3(
          this,
          Invocation.method(
            #getLeaderboard,
            [
              unit,
              size,
              offset,
            ],
          ),
        )),
      ) as _i15.Future<_i4.GetLeaderboardResponse>);
  @override
  _i15.Future<List<_i17.Prompt>> getPrompts(String? tokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrompts,
          [tokenId],
        ),
        returnValue: _i15.Future<List<_i17.Prompt>>.value(<_i17.Prompt>[]),
      ) as _i15.Future<List<_i17.Prompt>>);
}

/// A class which mocks [TezosService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTezosService extends _i1.Mock implements _i18.TezosService {
  MockTezosService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<int> getBalance(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [address],
        ),
        returnValue: _i15.Future<int>.value(0),
      ) as _i15.Future<int>);
  @override
  _i15.Future<int> estimateOperationFee(
    String? publicKey,
    List<_i5.Operation>? operations, {
    int? baseOperationCustomFee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateOperationFee,
          [
            publicKey,
            operations,
          ],
          {#baseOperationCustomFee: baseOperationCustomFee},
        ),
        returnValue: _i15.Future<int>.value(0),
      ) as _i15.Future<int>);
  @override
  _i15.Future<int> estimateFee(
    String? publicKey,
    String? to,
    int? amount, {
    int? baseOperationCustomFee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateFee,
          [
            publicKey,
            to,
            amount,
          ],
          {#baseOperationCustomFee: baseOperationCustomFee},
        ),
        returnValue: _i15.Future<int>.value(0),
      ) as _i15.Future<int>);
  @override
  _i15.Future<String?> sendOperationTransaction(
    _i10.WalletStorage? wallet,
    int? index,
    List<_i5.Operation>? operations, {
    int? baseOperationCustomFee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOperationTransaction,
          [
            wallet,
            index,
            operations,
          ],
          {#baseOperationCustomFee: baseOperationCustomFee},
        ),
        returnValue: _i15.Future<String?>.value(),
      ) as _i15.Future<String?>);
  @override
  _i15.Future<String?> sendTransaction(
    _i10.WalletStorage? wallet,
    int? index,
    String? to,
    int? amount, {
    int? baseOperationCustomFee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTransaction,
          [
            wallet,
            index,
            to,
            amount,
          ],
          {#baseOperationCustomFee: baseOperationCustomFee},
        ),
        returnValue: _i15.Future<String?>.value(),
      ) as _i15.Future<String?>);
  @override
  _i15.Future<String> signMessage(
    _i10.WalletStorage? wallet,
    int? index,
    _i19.Uint8List? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signMessage,
          [
            wallet,
            index,
            message,
          ],
        ),
        returnValue: _i15.Future<String>.value(''),
      ) as _i15.Future<String>);
  @override
  _i15.Future<_i5.Operation> getFa2TransferOperation(
    String? contract,
    String? from,
    String? to,
    String? tokenId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFa2TransferOperation,
          [
            contract,
            from,
            to,
            tokenId,
            quantity,
          ],
        ),
        returnValue: _i15.Future<_i5.Operation>.value(_FakeOperation_4(
          this,
          Invocation.method(
            #getFa2TransferOperation,
            [
              contract,
              from,
              to,
              tokenId,
              quantity,
            ],
          ),
        )),
      ) as _i15.Future<_i5.Operation>);
}

/// A class which mocks [IndexerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIndexerService extends _i1.Mock implements _i20.IndexerService {
  MockIndexerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<List<_i21.AssetToken>> getNftTokens(
          _i22.QueryListTokensRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNftTokens,
          [request],
        ),
        returnValue:
            _i15.Future<List<_i21.AssetToken>>.value(<_i21.AssetToken>[]),
      ) as _i15.Future<List<_i21.AssetToken>>);
  @override
  _i15.Future<_i6.BlockchainIdentity> getIdentity(
          _i23.QueryIdentityRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdentity,
          [request],
        ),
        returnValue:
            _i15.Future<_i6.BlockchainIdentity>.value(_FakeBlockchainIdentity_5(
          this,
          Invocation.method(
            #getIdentity,
            [request],
          ),
        )),
      ) as _i15.Future<_i6.BlockchainIdentity>);
}

/// A class which mocks [ConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationService extends _i1.Mock
    implements _i24.ConfigurationService {
  MockConfigurationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ValueNotifier<bool> get showNotifTip => (super.noSuchMethod(
        Invocation.getter(#showNotifTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showNotifTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showProTip => (super.noSuchMethod(
        Invocation.getter(#showProTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showProTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showTvAppTip => (super.noSuchMethod(
        Invocation.getter(#showTvAppTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showTvAppTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showCreatePlaylistTip => (super.noSuchMethod(
        Invocation.getter(#showCreatePlaylistTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showCreatePlaylistTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showLinkOrImportTip => (super.noSuchMethod(
        Invocation.getter(#showLinkOrImportTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showLinkOrImportTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showBackupSettingTip => (super.noSuchMethod(
        Invocation.getter(#showBackupSettingTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showBackupSettingTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i7.ValueNotifier<bool> get showWhatNewAddressTip => (super.noSuchMethod(
        Invocation.getter(#showWhatNewAddressTip),
        returnValue: _FakeValueNotifier_6<bool>(
          this,
          Invocation.getter(#showWhatNewAddressTip),
        ),
      ) as _i7.ValueNotifier<bool>);
  @override
  _i15.Future<void> setHasMerchandiseSupport(
    String? indexId, {
    bool? value = true,
    bool? isOverride = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHasMerchandiseSupport,
          [indexId],
          {
            #value: value,
            #isOverride: isOverride,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool hasMerchandiseSupport(String? indexId) => (super.noSuchMethod(
        Invocation.method(
          #hasMerchandiseSupport,
          [indexId],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setPostcardChatConfig(_i8.PostcardChatConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPostcardChatConfig,
          [config],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i8.PostcardChatConfig getPostcardChatConfig({
    required String? address,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostcardChatConfig,
          [],
          {
            #address: address,
            #id: id,
          },
        ),
        returnValue: _FakePostcardChatConfig_7(
          this,
          Invocation.method(
            #getPostcardChatConfig,
            [],
            {
              #address: address,
              #id: id,
            },
          ),
        ),
      ) as _i8.PostcardChatConfig);
  @override
  _i15.Future<void> setDidMigrateAddress(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDidMigrateAddress,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool getDidMigrateAddress() => (super.noSuchMethod(
        Invocation.method(
          #getDidMigrateAddress,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setAnnouncementLastPullTime(int? lastPullTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAnnouncementLastPullTime,
          [lastPullTime],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setOldUser() => (super.noSuchMethod(
        Invocation.method(
          #setOldUser,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool getIsOldUser() => (super.noSuchMethod(
        Invocation.method(
          #getIsOldUser,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setIAPReceipt(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPReceipt,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setIAPJWT(_i25.JWT? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPJWT,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setPremium(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setPremium,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isPremium() => (super.noSuchMethod(
        Invocation.method(
          #isPremium,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setDevicePasscodeEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDevicePasscodeEnabled,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isDevicePasscodeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDevicePasscodeEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setNotificationEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationEnabled,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setAnalyticEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticEnabled,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setDoneOnboarding(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboarding,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isDoneOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setPendingSettings(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setPendingSettings,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool hasPendingSettings() => (super.noSuchMethod(
        Invocation.method(
          #hasPendingSettings,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool shouldShowSubscriptionHint() => (super.noSuchMethod(
        Invocation.method(
          #shouldShowSubscriptionHint,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<dynamic> setShouldShowSubscriptionHint(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShouldShowSubscriptionHint,
          [value],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setLastTimeAskForSubscription(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastTimeAskForSubscription,
          [date],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<void> setDoneOnboardingOnce(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingOnce,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isDoneOnboardingOnce() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboardingOnce,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> readRemoveSupport(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #readRemoveSupport,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isReadRemoveSupport() => (super.noSuchMethod(
        Invocation.method(
          #isReadRemoveSupport,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setHideLinkedAccountInGallery(
    List<String>? address,
    bool? isEnabled, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
          {#override: override},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<String> getLinkedAccountsHiddenInGallery() => (super.noSuchMethod(
        Invocation.method(
          #getLinkedAccountsHiddenInGallery,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  bool isLinkedAccountHiddenInGallery(String? value) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [value],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<String> getTempStorageHiddenTokenIDs({_i26.Network? network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTempStorageHiddenTokenIDs,
          [],
          {#network: network},
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i15.Future<dynamic> updateTempStorageHiddenTokenIDs(
    List<String>? tokenIDs,
    bool? isAdd, {
    _i26.Network? network,
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTempStorageHiddenTokenIDs,
          [
            tokenIDs,
            isAdd,
          ],
          {
            #network: network,
            #override: override,
          },
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  List<_i27.SentArtwork> getRecentlySentToken() => (super.noSuchMethod(
        Invocation.method(
          #getRecentlySentToken,
          [],
        ),
        returnValue: <_i27.SentArtwork>[],
      ) as List<_i27.SentArtwork>);
  @override
  _i15.Future<dynamic> updateRecentlySentToken(
    List<_i27.SentArtwork>? sentArtwork, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecentlySentToken,
          [sentArtwork],
          {#override: override},
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<void> setReadReleaseNotesInVersion(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadReleaseNotesInVersion,
          [version],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setPreviousBuildNumber(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreviousBuildNumber,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<_i28.PlayListModel> getPlayList() => (super.noSuchMethod(
        Invocation.method(
          #getPlayList,
          [],
        ),
        returnValue: <_i28.PlayListModel>[],
      ) as List<_i28.PlayListModel>);
  @override
  _i15.Future<void> setPlayList(
    List<_i28.PlayListModel>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlayList,
          [value],
          {#override: override},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> removePlayList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removePlayList,
          [id],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<String> getAccountHMACSecret() => (super.noSuchMethod(
        Invocation.method(
          #getAccountHMACSecret,
          [],
        ),
        returnValue: _i15.Future<String>.value(''),
      ) as _i15.Future<String>);
  @override
  _i15.Future<void> setLastRemindReviewDate(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastRemindReviewDate,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setCountOpenApp(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setCountOpenApp,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #isDemoArtworksMode,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<bool> toggleDemoArtworksMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleDemoArtworksMode,
          [],
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);
  @override
  bool showTokenDebugInfo() => (super.noSuchMethod(
        Invocation.method(
          #showTokenDebugInfo,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<dynamic> setShowTokenDebugInfo(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTokenDebugInfo,
          [show],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setDoneOnboardingTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingTime,
          [time],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setSubscriptionTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionTime,
          [time],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setAlreadyShowProTip(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowProTip,
          [show],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setAlreadyShowTvAppTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowTvAppTip,
          [show],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setAlreadyShowCreatePlaylistTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowCreatePlaylistTip,
          [show],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setAlreadyShowLinkOrImportTip(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowLinkOrImportTip,
          [show],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  bool getAlreadyShowProTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowProTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowTvAppTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowTvAppTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowCreatePlaylistTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowCreatePlaylistTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool getAlreadyShowLinkOrImportTip() => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowLinkOrImportTip,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<dynamic> setShowBackupSettingTip(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowBackupSettingTip,
          [time],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  bool getShowWhatNewAddressTip(int? currentVersion) => (super.noSuchMethod(
        Invocation.method(
          #getShowWhatNewAddressTip,
          [currentVersion],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<dynamic> setShowWhatNewAddressTipRead(int? currentVersion) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowWhatNewAddressTipRead,
          [currentVersion],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setSentTezosArtworkMetric(int? hashedAddresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSentTezosArtworkMetric,
          [hashedAddresses],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<_i29.SharedPostcard> getSharedPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getSharedPostcard,
          [],
        ),
        returnValue: <_i29.SharedPostcard>[],
      ) as List<_i29.SharedPostcard>);
  @override
  _i15.Future<void> updateSharedPostcard(
    List<_i29.SharedPostcard>? sharedPostcards, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedPostcard,
          [sharedPostcards],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> removeSharedPostcardWhere(
          bool Function(_i29.SharedPostcard)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSharedPostcardWhere,
          [test],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<String> getListPostcardMint() => (super.noSuchMethod(
        Invocation.method(
          #getListPostcardMint,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i15.Future<void> setListPostcardMint(
    List<String>? tokenID, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardMint,
          [tokenID],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<_i30.StampingPostcard> getStampingPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getStampingPostcard,
          [],
        ),
        returnValue: <_i30.StampingPostcard>[],
      ) as List<_i30.StampingPostcard>);
  @override
  _i15.Future<void> updateStampingPostcard(
    List<_i30.StampingPostcard>? values, {
    bool? override = false,
    bool? isRemove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStampingPostcard,
          [values],
          {
            #override: override,
            #isRemove: isRemove,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setProcessingStampPostcard(
    List<_i30.ProcessingStampPostcard>? values, {
    bool? override = false,
    bool? isRemove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setProcessingStampPostcard,
          [values],
          {
            #override: override,
            #isRemove: isRemove,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<_i30.ProcessingStampPostcard> getProcessingStampPostcard() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProcessingStampPostcard,
          [],
        ),
        returnValue: <_i30.ProcessingStampPostcard>[],
      ) as List<_i30.ProcessingStampPostcard>);
  @override
  _i15.Future<void> setAutoShowPostcard(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoShowPostcard,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isAutoShowPostcard() => (super.noSuchMethod(
        Invocation.method(
          #isAutoShowPostcard,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<_i31.PostcardIdentity> getListPostcardAlreadyShowYouDidIt() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListPostcardAlreadyShowYouDidIt,
          [],
        ),
        returnValue: <_i31.PostcardIdentity>[],
      ) as List<_i31.PostcardIdentity>);
  @override
  _i15.Future<void> setListPostcardAlreadyShowYouDidIt(
    List<_i31.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardAlreadyShowYouDidIt,
          [value],
          {#override: override},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setAlreadyShowPostcardUpdates(
    List<_i31.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowPostcardUpdates,
          [value],
          {#override: override},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  List<_i31.PostcardIdentity> getAlreadyShowPostcardUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowPostcardUpdates,
          [],
        ),
        returnValue: <_i31.PostcardIdentity>[],
      ) as List<_i31.PostcardIdentity>);
  @override
  String getVersionInfo() => (super.noSuchMethod(
        Invocation.method(
          #getVersionInfo,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i15.Future<void> setVersionInfo(String? version) => (super.noSuchMethod(
        Invocation.method(
          #setVersionInfo,
          [version],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> updateShowAnnouncementNotificationInfo(
          _i32.AnnouncementLocal? announcement) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShowAnnouncementNotificationInfo,
          [announcement],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i9.ShowAnouncementNotificationInfo getShowAnnouncementNotificationInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getShowAnnouncementNotificationInfo,
          [],
        ),
        returnValue: _FakeShowAnouncementNotificationInfo_8(
          this,
          Invocation.method(
            #getShowAnnouncementNotificationInfo,
            [],
          ),
        ),
      ) as _i9.ShowAnouncementNotificationInfo);
  @override
  bool getAlreadyClaimedAirdrop(String? seriesId) => (super.noSuchMethod(
        Invocation.method(
          #getAlreadyClaimedAirdrop,
          [seriesId],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> setAlreadyClaimedAirdrop(
    String? seriesId,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyClaimedAirdrop,
          [
            seriesId,
            value,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> setDidSyncArtists(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDidSyncArtists,
          [value],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool getDidSyncArtists() => (super.noSuchMethod(
        Invocation.method(
          #getDidSyncArtists,
          [],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i33.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i10.WalletStorage> getDefaultAccount() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultAccount,
          [],
        ),
        returnValue: _i15.Future<_i10.WalletStorage>.value(_FakeWalletStorage_9(
          this,
          Invocation.method(
            #getDefaultAccount,
            [],
          ),
        )),
      ) as _i15.Future<_i10.WalletStorage>);
  @override
  _i15.Future<_i11.Persona> getOrCreateDefaultPersona() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateDefaultPersona,
          [],
        ),
        returnValue: _i15.Future<_i11.Persona>.value(_FakePersona_10(
          this,
          Invocation.method(
            #getOrCreateDefaultPersona,
            [],
          ),
        )),
      ) as _i15.Future<_i11.Persona>);
  @override
  _i15.Future<_i10.WalletStorage?> getCurrentDefaultAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentDefaultAccount,
          [],
        ),
        returnValue: _i15.Future<_i10.WalletStorage?>.value(),
      ) as _i15.Future<_i10.WalletStorage?>);
  @override
  _i15.Future<_i12.WalletIndex> getAccountByAddress({
    required String? chain,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountByAddress,
          [],
          {
            #chain: chain,
            #address: address,
          },
        ),
        returnValue: _i15.Future<_i12.WalletIndex>.value(_FakeWalletIndex_11(
          this,
          Invocation.method(
            #getAccountByAddress,
            [],
            {
              #chain: chain,
              #address: address,
            },
          ),
        )),
      ) as _i15.Future<_i12.WalletIndex>);
  @override
  _i15.Future<dynamic> androidBackupKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidBackupKeys,
          [],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<List<_i13.Connection>> removeDoubleViewOnly(
          List<String>? addresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDoubleViewOnly,
          [addresses],
        ),
        returnValue:
            _i15.Future<List<_i13.Connection>>.value(<_i13.Connection>[]),
      ) as _i15.Future<List<_i13.Connection>>);
  @override
  _i15.Future<bool?> isAndroidEndToEndEncryptionAvailable() =>
      (super.noSuchMethod(
        Invocation.method(
          #isAndroidEndToEndEncryptionAvailable,
          [],
        ),
        returnValue: _i15.Future<bool?>.value(),
      ) as _i15.Future<bool?>);
  @override
  _i15.Future<dynamic> androidRestoreKeys() => (super.noSuchMethod(
        Invocation.method(
          #androidRestoreKeys,
          [],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<_i11.Persona> createPersona({
    String? name = r'',
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPersona,
          [],
          {
            #name: name,
            #isDefault: isDefault,
          },
        ),
        returnValue: _i15.Future<_i11.Persona>.value(_FakePersona_10(
          this,
          Invocation.method(
            #createPersona,
            [],
            {
              #name: name,
              #isDefault: isDefault,
            },
          ),
        )),
      ) as _i15.Future<_i11.Persona>);
  @override
  _i15.Future<_i11.Persona> importPersona(
    String? words, {
    _i34.WalletType? walletType = _i34.WalletType.Autonomy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importPersona,
          [words],
          {#walletType: walletType},
        ),
        returnValue: _i15.Future<_i11.Persona>.value(_FakePersona_10(
          this,
          Invocation.method(
            #importPersona,
            [words],
            {#walletType: walletType},
          ),
        )),
      ) as _i15.Future<_i11.Persona>);
  @override
  _i15.Future<_i13.Connection> nameLinkedAccount(
    _i13.Connection? connection,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #nameLinkedAccount,
          [
            connection,
            name,
          ],
        ),
        returnValue: _i15.Future<_i13.Connection>.value(_FakeConnection_12(
          this,
          Invocation.method(
            #nameLinkedAccount,
            [
              connection,
              name,
            ],
          ),
        )),
      ) as _i15.Future<_i13.Connection>);
  @override
  _i15.Future<_i13.Connection> linkManuallyAddress(
    String? address,
    _i35.CryptoType? cryptoType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkManuallyAddress,
          [
            address,
            cryptoType,
          ],
        ),
        returnValue: _i15.Future<_i13.Connection>.value(_FakeConnection_12(
          this,
          Invocation.method(
            #linkManuallyAddress,
            [
              address,
              cryptoType,
            ],
          ),
        )),
      ) as _i15.Future<_i13.Connection>);
  @override
  _i15.Future<dynamic> deletePersona(_i11.Persona? persona) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePersona,
          [persona],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> deleteLinkedAccount(_i13.Connection? connection) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLinkedAccount,
          [connection],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> linkIndexerTokenID(String? indexerTokenID) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkIndexerTokenID,
          [indexerTokenID],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setHideLinkedAccountInGallery(
    String? address,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideLinkedAccountInGallery,
          [
            address,
            isEnabled,
          ],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> setHideAddressInGallery(
    List<String>? addresses,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideAddressInGallery,
          [
            addresses,
            isEnabled,
          ],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  bool isLinkedAccountHiddenInGallery(String? address) => (super.noSuchMethod(
        Invocation.method(
          #isLinkedAccountHiddenInGallery,
          [address],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<List<String>> getAllAddresses({bool? logHiddenAddress = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAddresses,
          [],
          {#logHiddenAddress: logHiddenAddress},
        ),
        returnValue: _i15.Future<List<String>>.value(<String>[]),
      ) as _i15.Future<List<String>>);
  @override
  _i15.Future<List<_i36.AddressIndex>> getAllAddressIndexes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAddressIndexes,
          [],
        ),
        returnValue:
            _i15.Future<List<_i36.AddressIndex>>.value(<_i36.AddressIndex>[]),
      ) as _i15.Future<List<_i36.AddressIndex>>);
  @override
  _i15.Future<List<String>> getAddress(
    String? blockchain, {
    bool? withViewOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddress,
          [blockchain],
          {#withViewOnly: withViewOnly},
        ),
        returnValue: _i15.Future<List<String>>.value(<String>[]),
      ) as _i15.Future<List<String>>);
  @override
  _i15.Future<List<_i36.AddressIndex>> getHiddenAddressIndexes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHiddenAddressIndexes,
          [],
        ),
        returnValue:
            _i15.Future<List<_i36.AddressIndex>>.value(<_i36.AddressIndex>[]),
      ) as _i15.Future<List<_i36.AddressIndex>>);
  @override
  _i15.Future<List<String>> getShowedAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getShowedAddresses,
          [],
        ),
        returnValue: _i15.Future<List<String>>.value(<String>[]),
      ) as _i15.Future<List<String>>);
  @override
  _i15.Future<bool> addAddressPersona(
    _i11.Persona? newPersona,
    List<_i37.AddressInfo>? addresses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAddressPersona,
          [
            newPersona,
            addresses,
          ],
        ),
        returnValue: _i15.Future<bool>.value(false),
      ) as _i15.Future<bool>);
  @override
  _i15.Future<void> deleteAddressPersona(
    _i11.Persona? persona,
    _i38.WalletAddress? walletAddress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAddressPersona,
          [
            persona,
            walletAddress,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<_i38.WalletAddress?> getAddressPersona(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressPersona,
          [address],
        ),
        returnValue: _i15.Future<_i38.WalletAddress?>.value(),
      ) as _i15.Future<_i38.WalletAddress?>);
  @override
  _i15.Future<void> updateAddressPersona(_i38.WalletAddress? walletAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddressPersona,
          [walletAddress],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> restoreIfNeeded({bool? isCreateNew = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreIfNeeded,
          [],
          {#isCreateNew: isCreateNew},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}

/// A class which mocks [TokensService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokensService extends _i1.Mock implements _i39.TokensService {
  MockTokensService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRefreshAllTokensListen => (super.noSuchMethod(
        Invocation.getter(#isRefreshAllTokensListen),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<dynamic> fetchTokensForAddresses(List<String>? addresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTokensForAddresses,
          [addresses],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<List<_i21.AssetToken>> fetchManualTokens(
          List<String>? indexerIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchManualTokens,
          [indexerIds],
        ),
        returnValue:
            _i15.Future<List<_i21.AssetToken>>.value(<_i21.AssetToken>[]),
      ) as _i15.Future<List<_i21.AssetToken>>);
  @override
  _i15.Future<dynamic> setCustomTokens(List<_i21.AssetToken>? assetTokens) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomTokens,
          [assetTokens],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<_i15.Stream<List<_i21.AssetToken>>> refreshTokensInIsolate(
          Map<int, List<String>>? addresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshTokensInIsolate,
          [addresses],
        ),
        returnValue: _i15.Future<_i15.Stream<List<_i21.AssetToken>>>.value(
            _i15.Stream<List<_i21.AssetToken>>.empty()),
      ) as _i15.Future<_i15.Stream<List<_i21.AssetToken>>>);
  @override
  _i15.Future<dynamic> reindexAddresses(List<String>? addresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #reindexAddresses,
          [addresses],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> purgeCachedGallery() => (super.noSuchMethod(
        Invocation.method(
          #purgeCachedGallery,
          [],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
  @override
  _i15.Future<dynamic> postPendingToken(_i40.PendingTxParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPendingToken,
          [params],
        ),
        returnValue: _i15.Future<dynamic>.value(),
      ) as _i15.Future<dynamic>);
}

/// A class which mocks [MetricClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricClientService extends _i1.Mock
    implements _i41.MetricClientService {
  MockMetricClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set useAppTimer(_i15.Timer? _useAppTimer) => super.noSuchMethod(
        Invocation.setter(
          #useAppTimer,
          _useAppTimer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i14.MixPanelClientService get mixPanelClient => (super.noSuchMethod(
        Invocation.getter(#mixPanelClient),
        returnValue: _FakeMixPanelClientService_13(
          this,
          Invocation.getter(#mixPanelClient),
        ),
      ) as _i14.MixPanelClientService);
  @override
  bool get isFinishInit => (super.noSuchMethod(
        Invocation.getter(#isFinishInit),
        returnValue: false,
      ) as bool);
  @override
  set isFinishInit(bool? _isFinishInit) => super.noSuchMethod(
        Invocation.setter(
          #isFinishInit,
          _isFinishInit,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i15.Future<void> initService() => (super.noSuchMethod(
        Invocation.method(
          #initService,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> refreshNumberNfts() => (super.noSuchMethod(
        Invocation.method(
          #refreshNumberNfts,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> addEvent(
    String? name, {
    String? message,
    Map<String, dynamic>? data = const {},
    Map<String, dynamic>? hashedData = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [name],
          {
            #message: message,
            #data: data,
            #hashedData: hashedData,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  dynamic timerEvent(String? name) => super.noSuchMethod(Invocation.method(
        #timerEvent,
        [name],
      ));
  @override
  _i15.Future<void> sendAndClearMetrics() => (super.noSuchMethod(
        Invocation.method(
          #sendAndClearMetrics,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> trackStartScreen(String? screen) => (super.noSuchMethod(
        Invocation.method(
          #trackStartScreen,
          [screen],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> trackEndScreen(String? screen) => (super.noSuchMethod(
        Invocation.method(
          #trackEndScreen,
          [screen],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  void setLabel(
    String? prop,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void incrementPropertyLabel(
    String? prop,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #incrementPropertyLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onAddConnection(_i13.Connection? connection) => super.noSuchMethod(
        Invocation.method(
          #onAddConnection,
          [connection],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onRemoveConnection(_i13.Connection? connection) => super.noSuchMethod(
        Invocation.method(
          #onRemoveConnection,
          [connection],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onRestore() => super.noSuchMethod(
        Invocation.method(
          #onRestore,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i15.Future<void> initConfigIfNeed(Map<String, dynamic>? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #initConfigIfNeed,
          [config],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  dynamic getConfig(
    String? key, {
    dynamic defaultValue,
  }) =>
      super.noSuchMethod(Invocation.method(
        #getConfig,
        [key],
        {#defaultValue: defaultValue},
      ));
  @override
  _i15.Future<void> setConfig(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [
            key,
            value,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> onOpenApp() => (super.noSuchMethod(
        Invocation.method(
          #onOpenApp,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> onUseAppInForeground() => (super.noSuchMethod(
        Invocation.method(
          #onUseAppInForeground,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i42.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<void> connect({
    required String? address,
    required String? id,
    required _i43.Pair<_i10.WalletStorage, int>? wallet,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #address: address,
            #id: id,
            #wallet: wallet,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  void addListener(_i42.ChatListener? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i15.Future<void> removeListener(_i42.ChatListener? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  void sendMessage(
    dynamic message, {
    String? listenerId,
    String? requestId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
          {
            #listenerId: listenerId,
            #requestId: requestId,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i15.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  bool isConnecting({
    required String? address,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isConnecting,
          [],
          {
            #address: address,
            #id: id,
          },
        ),
        returnValue: false,
      ) as bool);
  @override
  _i15.Future<void> reconnect() => (super.noSuchMethod(
        Invocation.method(
          #reconnect,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
  @override
  _i15.Future<void> sendPostcardCompleteMessage(
    String? address,
    String? id,
    _i43.Pair<_i10.WalletStorage, int>? wallet,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPostcardCompleteMessage,
          [
            address,
            id,
            wallet,
          ],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}
