// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_metric_client_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:autonomy_flutter/service/metric_client_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MetricClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricClientService extends _i1.Mock
    implements _i2.MetricClientService {
  MockMetricClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get _isFinishInit => (super.noSuchMethod(
        Invocation.getter(#isFinishInit),
        returnValue: false,
      ) as bool);
  @override
  set _isFinishInit(bool? _isFinishInit) => super.noSuchMethod(
        Invocation.setter(
          #isFinishInit,
          _isFinishInit,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<void> initService() => (super.noSuchMethod(
        Invocation.method(
          #initService,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  void addEvent(
    String? name, {
    String? message,
    Map<String, dynamic>? data = const {},
    Map<String, dynamic>? hashedData = const {},
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [name],
          {
            #message: message,
            #data: data,
            #hashedData: hashedData,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void timerEvent(String? name) => super.noSuchMethod(
        Invocation.method(
          #timerEvent,
          [name],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<void> mergeUser(String? oldUserId) => (super.noSuchMethod(
        Invocation.method(
          #mergeUser,
          [oldUserId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  void setLabel(
    String? prop,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void incrementPropertyLabel(
    String? prop,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #incrementPropertyLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
