// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_metric_client_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:autonomy_flutter/service/metric_client_service.dart' as _i3;
import 'package:autonomy_flutter/service/mix_panel_client_service.dart' as _i2;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMixPanelClientService_0 extends _i1.SmartFake
    implements _i2.MixPanelClientService {
  _FakeMixPanelClientService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MetricClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricClientService extends _i1.Mock
    implements _i3.MetricClientService {
  MockMetricClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MixPanelClientService get mixPanelClient => (super.noSuchMethod(
        Invocation.getter(#mixPanelClient),
        returnValue: _FakeMixPanelClientService_0(
          this,
          Invocation.getter(#mixPanelClient),
        ),
      ) as _i2.MixPanelClientService);
  @override
  bool get isFinishInit => (super.noSuchMethod(
        Invocation.getter(#isFinishInit),
        returnValue: false,
      ) as bool);
  @override
  set isFinishInit(bool? _isFinishInit) => super.noSuchMethod(
        Invocation.setter(
          #isFinishInit,
          _isFinishInit,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> initService() => (super.noSuchMethod(
        Invocation.method(
          #initService,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> migrateFromDidKeyToPrimaryAddress() => (super.noSuchMethod(
        Invocation.method(
          #migrateFromDidKeyToPrimaryAddress,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void addEvent(
    String? name, {
    String? message,
    Map<String, dynamic>? data = const {},
    Map<String, dynamic>? hashedData = const {},
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [name],
          {
            #message: message,
            #data: data,
            #hashedData: hashedData,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void timerEvent(String? name) => super.noSuchMethod(
        Invocation.method(
          #timerEvent,
          [name],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> sendAndClearMetrics() => (super.noSuchMethod(
        Invocation.method(
          #sendAndClearMetrics,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> trackStartScreen(_i5.Route<dynamic>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackStartScreen,
          [route],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> trackEndScreen(_i5.Route<dynamic>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEndScreen,
          [route],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void setLabel(
    String? prop,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void incrementPropertyLabel(
    String? prop,
    double? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #incrementPropertyLabel,
          [
            prop,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> initConfigIfNeed(Map<String, dynamic>? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #initConfigIfNeed,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  dynamic getConfig(
    String? key, {
    dynamic defaultValue,
  }) =>
      super.noSuchMethod(Invocation.method(
        #getConfig,
        [key],
        {#defaultValue: defaultValue},
      ));
  @override
  _i4.Future<void> setConfig(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void onBackground() => super.noSuchMethod(
        Invocation.method(
          #onBackground,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onForeground() => super.noSuchMethod(
        Invocation.method(
          #onForeground,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
