// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_navigation_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i11;

import 'package:autonomy_flutter/model/canvas_device_info.dart' as _i14;
import 'package:autonomy_flutter/model/ff_exhibition.dart' as _i9;
import 'package:autonomy_flutter/model/play_list_model.dart' as _i10;
import 'package:autonomy_flutter/screen/irl_screen/webview_irl_screen.dart'
    as _i8;
import 'package:autonomy_flutter/screen/settings/subscription/upgrade_state.dart'
    as _i7;
import 'package:autonomy_flutter/service/navigation_service.dart' as _i3;
import 'package:autonomy_flutter/util/error_handler.dart' as _i6;
import 'package:autonomy_flutter/view/display_instruction_view.dart' as _i13;
import 'package:flutter/material.dart' as _i1;
import 'package:flutter_vibrate/flutter_vibrate.dart' as _i12;
import 'package:mockito/mockito.dart' as _i2;
import 'package:nft_collection/models/asset_token.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_1 extends _i2.SmartFake implements _i1.BuildContext {
  _FakeBuildContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNavigatorState_2 extends _i2.SmartFake
    implements _i1.NavigatorState {
  _FakeNavigatorState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i1.DiagnosticLevel? minLevel = _i1.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i2.Mock implements _i3.NavigationService {
  MockNavigationService() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i1.GlobalKey<_i1.NavigatorState>);
  @override
  _i1.BuildContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeBuildContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i1.BuildContext);
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);
  @override
  void setGlobalHomeTabController(_i1.PageController? controller) =>
      super.noSuchMethod(
        Invocation.method(
          #setGlobalHomeTabController,
          [controller],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<dynamic>? navigateTo(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #navigateTo,
        [routeName],
        {#arguments: arguments},
      )) as _i4.Future<dynamic>?);
  @override
  _i4.Future<dynamic>? popAndPushNamed(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #popAndPushNamed,
        [routeName],
        {#arguments: arguments},
      )) as _i4.Future<dynamic>?);
  @override
  _i4.Future<void> selectPromptsThenStamp(
    _i1.BuildContext? context,
    _i5.AssetToken? asset,
    String? shareCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectPromptsThenStamp,
          [
            context,
            asset,
            shareCode,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<dynamic>? navigateUntil(
    String? routeName,
    _i1.RoutePredicate? predicate, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #navigateUntil,
        [
          routeName,
          predicate,
        ],
        {#arguments: arguments},
      )) as _i4.Future<dynamic>?);
  @override
  _i1.NavigatorState navigatorState() => (super.noSuchMethod(
        Invocation.method(
          #navigatorState,
          [],
        ),
        returnValue: _FakeNavigatorState_2(
          this,
          Invocation.method(
            #navigatorState,
            [],
          ),
        ),
      ) as _i1.NavigatorState);
  @override
  void showErrorDialog(
    _i6.ErrorEvent? event, {
    dynamic Function()? defaultAction,
    dynamic Function()? cancelAction,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showErrorDialog,
          [event],
          {
            #defaultAction: defaultAction,
            #cancelAction: cancelAction,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void hideInfoDialog() => super.noSuchMethod(
        Invocation.method(
          #hideInfoDialog,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> showAppLoadError() => (super.noSuchMethod(
        Invocation.method(
          #showAppLoadError,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void goBack({Object? result}) => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popUntilHome() => super.noSuchMethod(
        Invocation.method(
          #popUntilHome,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popUntilHomeOrSettings() => super.noSuchMethod(
        Invocation.method(
          #popUntilHomeOrSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setIsWCConnectInShow(bool? appeared) => super.noSuchMethod(
        Invocation.method(
          #setIsWCConnectInShow,
          [appeared],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> showContactingDialog() => (super.noSuchMethod(
        Invocation.method(
          #showContactingDialog,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> waitTooLongDialog() => (super.noSuchMethod(
        Invocation.method(
          #waitTooLongDialog,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> addressNotFoundError() => (super.noSuchMethod(
        Invocation.method(
          #addressNotFoundError,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showCannotConnectTv() => (super.noSuchMethod(
        Invocation.method(
          #showCannotConnectTv,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showUnknownLink() => (super.noSuchMethod(
        Invocation.method(
          #showUnknownLink,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showCannotResolveBranchLink() => (super.noSuchMethod(
        Invocation.method(
          #showCannotResolveBranchLink,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showMembershipGiftCodeEmpty() => (super.noSuchMethod(
        Invocation.method(
          #showMembershipGiftCodeEmpty,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showFailToRedeemMembership() => (super.noSuchMethod(
        Invocation.method(
          #showFailToRedeemMembership,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showRedeemMembershipCodeUsed() => (super.noSuchMethod(
        Invocation.method(
          #showRedeemMembershipCodeUsed,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPremiumUserCanNotClaim() => (super.noSuchMethod(
        Invocation.method(
          #showPremiumUserCanNotClaim,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showRedeemMembershipSuccess() => (super.noSuchMethod(
        Invocation.method(
          #showRedeemMembershipSuccess,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showDeclinedGeolocalization() => (super.noSuchMethod(
        Invocation.method(
          #showDeclinedGeolocalization,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showSeeMoreArtNow(
          _i7.SubscriptionDetails? subscriptionDetails) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSeeMoreArtNow,
          [subscriptionDetails],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openPostcardReceivedPage({
    required _i5.AssetToken? asset,
    required String? shareCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPostcardReceivedPage,
          [],
          {
            #asset: asset,
            #shareCode: shareCode,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> gotoExhibitionDetailsPage(String? exhibitionID) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoExhibitionDetailsPage,
          [exhibitionID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> popToCollection() => (super.noSuchMethod(
        Invocation.method(
          #popToCollection,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> gotoArtworkDetailsPage(String? indexID) =>
      (super.noSuchMethod(
        Invocation.method(
          #gotoArtworkDetailsPage,
          [indexID],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<dynamic> goToIRLWebview(_i8.IRLWebScreenPayload? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #goToIRLWebview,
          [payload],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
  @override
  _i4.Future<void> showAlreadyDeliveredPostcard() => (super.noSuchMethod(
        Invocation.method(
          #showAlreadyDeliveredPostcard,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardShareLinkExpired() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardShareLinkExpired,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardShareLinkInvalid() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardShareLinkInvalid,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showLocationExplain() => (super.noSuchMethod(
        Invocation.method(
          #showLocationExplain,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardRunOut() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardRunOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardQRCodeExpired() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardQRCodeExpired,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardClaimLimited() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardClaimLimited,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showPostcardNotInMiami() => (super.noSuchMethod(
        Invocation.method(
          #showPostcardNotInMiami,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openAutonomyDocument(
    String? href,
    String? title,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openAutonomyDocument,
          [
            href,
            title,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openFeralFileArtistPage(String? id) => (super.noSuchMethod(
        Invocation.method(
          #openFeralFileArtistPage,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openFeralFileCuratorPage(String? id) => (super.noSuchMethod(
        Invocation.method(
          #openFeralFileCuratorPage,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openFeralFileExhibitionNotePage(String? exhibitionSlug) =>
      (super.noSuchMethod(
        Invocation.method(
          #openFeralFileExhibitionNotePage,
          [exhibitionSlug],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openCollection() => (super.noSuchMethod(
        Invocation.method(
          #openCollection,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openFeralFilePostPage(
    _i9.Post? post,
    String? exhibitionID,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openFeralFilePostPage,
          [
            post,
            exhibitionID,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> navigatePath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #navigatePath,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showEnvKeyIsMissing(List<String>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #showEnvKeyIsMissing,
          [keys],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openPlaylist({required _i10.PlayListModel? playlist}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPlaylist,
          [],
          {#playlist: playlist},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showALreadyClaimPlaylist(
          {required _i10.PlayListModel? playlist}) =>
      (super.noSuchMethod(
        Invocation.method(
          #showALreadyClaimPlaylist,
          [],
          {#playlist: playlist},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void>? showPlaylistActivationExpired() => (super.noSuchMethod(
        Invocation.method(
          #showPlaylistActivationExpired,
          [],
        ),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>?);
  @override
  _i4.Future<void> showFlexibleDialog(
    _i1.Widget? content, {
    bool? isDismissible = false,
    bool? isRoundCorner = true,
    _i11.Color? backgroundColor,
    int? autoDismissAfter = 0,
    _i12.FeedbackType? feedback = _i12.FeedbackType.selection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showFlexibleDialog,
          [content],
          {
            #isDismissible: isDismissible,
            #isRoundCorner: isRoundCorner,
            #backgroundColor: backgroundColor,
            #autoDismissAfter: autoDismissAfter,
            #feedback: feedback,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showHowToDisplay(
    _i13.SupportedDisplayBranch? displayBranch,
    Function? onScanQRTap,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showHowToDisplay,
          [
            displayBranch,
            onScanQRTap,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showStreamAction(
    String? displayKey,
    dynamic Function(_i14.CanvasDevice)? onDeviceSelected,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showStreamAction,
          [
            displayKey,
            onDeviceSelected,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openUrl(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [uri],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
