// Mocks generated by Mockito 5.4.2 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_feral_file_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i9;

import 'package:autonomy_flutter/model/ff_account.dart' as _i4;
import 'package:autonomy_flutter/model/ff_exhibition.dart' as _i5;
import 'package:autonomy_flutter/model/ff_series.dart' as _i2;
import 'package:autonomy_flutter/model/otp.dart' as _i8;
import 'package:autonomy_flutter/screen/claim/claim_token_page.dart' as _i3;
import 'package:autonomy_flutter/service/feralfile_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nft_collection/models/asset_token.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFFSeries_0 extends _i1.SmartFake implements _i2.FFSeries {
  _FakeFFSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClaimResponse_1 extends _i1.SmartFake implements _i3.ClaimResponse {
  _FakeClaimResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeralFileResaleInfo_2 extends _i1.SmartFake
    implements _i4.FeralFileResaleInfo {
  _FakeFeralFileResaleInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExhibition_3 extends _i1.SmartFake implements _i5.Exhibition {
  _FakeExhibition_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArtwork_4 extends _i1.SmartFake implements _i4.Artwork {
  _FakeArtwork_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeralFileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeralFileService extends _i1.Mock implements _i6.FeralFileService {
  MockFeralFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.FFSeries> getAirdropSeriesFromExhibitionId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAirdropSeriesFromExhibitionId,
          [id],
        ),
        returnValue: _i7.Future<_i2.FFSeries>.value(_FakeFFSeries_0(
          this,
          Invocation.method(
            #getAirdropSeriesFromExhibitionId,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.FFSeries>);
  @override
  _i7.Future<_i2.FFSeries> getSeries(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSeries,
          [id],
        ),
        returnValue: _i7.Future<_i2.FFSeries>.value(_FakeFFSeries_0(
          this,
          Invocation.method(
            #getSeries,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.FFSeries>);
  @override
  _i7.Future<_i3.ClaimResponse> setPendingToken({
    required String? receiver,
    required _i4.TokenClaimResponse? response,
    required _i2.FFSeries? series,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPendingToken,
          [],
          {
            #receiver: receiver,
            #response: response,
            #series: series,
          },
        ),
        returnValue: _i7.Future<_i3.ClaimResponse>.value(_FakeClaimResponse_1(
          this,
          Invocation.method(
            #setPendingToken,
            [],
            {
              #receiver: receiver,
              #response: response,
              #series: series,
            },
          ),
        )),
      ) as _i7.Future<_i3.ClaimResponse>);
  @override
  _i7.Future<_i3.ClaimResponse?> claimToken({
    required String? seriesId,
    String? address,
    _i8.Otp? otp,
    _i7.Future<bool> Function(_i2.FFSeries)? onConfirm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimToken,
          [],
          {
            #seriesId: seriesId,
            #address: address,
            #otp: otp,
            #onConfirm: onConfirm,
          },
        ),
        returnValue: _i7.Future<_i3.ClaimResponse?>.value(),
      ) as _i7.Future<_i3.ClaimResponse?>);
  @override
  _i7.Future<_i5.Exhibition?> getExhibitionFromTokenID(String? artworkID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExhibitionFromTokenID,
          [artworkID],
        ),
        returnValue: _i7.Future<_i5.Exhibition?>.value(),
      ) as _i7.Future<_i5.Exhibition?>);
  @override
  _i7.Future<_i4.FeralFileResaleInfo> getResaleInfo(String? exhibitionID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResaleInfo,
          [exhibitionID],
        ),
        returnValue: _i7.Future<_i4.FeralFileResaleInfo>.value(
            _FakeFeralFileResaleInfo_2(
          this,
          Invocation.method(
            #getResaleInfo,
            [exhibitionID],
          ),
        )),
      ) as _i7.Future<_i4.FeralFileResaleInfo>);
  @override
  _i7.Future<String?> getPartnerFullName(String? exhibitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerFullName,
          [exhibitionId],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
  @override
  _i7.Future<_i5.Exhibition> getExhibition(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExhibition,
          [id],
        ),
        returnValue: _i7.Future<_i5.Exhibition>.value(_FakeExhibition_3(
          this,
          Invocation.method(
            #getExhibition,
            [id],
          ),
        )),
      ) as _i7.Future<_i5.Exhibition>);
  @override
  _i7.Future<List<_i5.ExhibitionDetail>> getAllExhibitions({
    String? sortBy = r'openAt',
    String? sortOrder = r'DESC',
    int? limit = 8,
    int? offset = 0,
    bool? withArtworks = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExhibitions,
          [],
          {
            #sortBy: sortBy,
            #sortOrder: sortOrder,
            #limit: limit,
            #offset: offset,
            #withArtworks: withArtworks,
          },
        ),
        returnValue: _i7.Future<List<_i5.ExhibitionDetail>>.value(
            <_i5.ExhibitionDetail>[]),
      ) as _i7.Future<List<_i5.ExhibitionDetail>>);
  @override
  _i7.Future<_i5.Exhibition> getFeaturedExhibition() => (super.noSuchMethod(
        Invocation.method(
          #getFeaturedExhibition,
          [],
        ),
        returnValue: _i7.Future<_i5.Exhibition>.value(_FakeExhibition_3(
          this,
          Invocation.method(
            #getFeaturedExhibition,
            [],
          ),
        )),
      ) as _i7.Future<_i5.Exhibition>);
  @override
  _i7.Future<List<_i4.Artwork>> getExhibitionArtworks(String? exhibitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExhibitionArtworks,
          [exhibitionId],
        ),
        returnValue: _i7.Future<List<_i4.Artwork>>.value(<_i4.Artwork>[]),
      ) as _i7.Future<List<_i4.Artwork>>);
  @override
  _i7.Future<List<_i4.Artwork>> getSeriesArtworks(String? seriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesArtworks,
          [seriesId],
        ),
        returnValue: _i7.Future<List<_i4.Artwork>>.value(<_i4.Artwork>[]),
      ) as _i7.Future<List<_i4.Artwork>>);
  @override
  _i7.Future<String> getFeralfileActionMessage({
    required String? address,
    required _i6.FeralfileAction? action,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeralfileActionMessage,
          [],
          {
            #address: address,
            #action: action,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> getFeralfileArtworkDownloadUrl({
    required String? artworkId,
    required String? owner,
    required String? signature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeralfileArtworkDownloadUrl,
          [],
          {
            #artworkId: artworkId,
            #owner: owner,
            #signature: signature,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i4.Artwork> getArtwork(String? artworkId) => (super.noSuchMethod(
        Invocation.method(
          #getArtwork,
          [artworkId],
        ),
        returnValue: _i7.Future<_i4.Artwork>.value(_FakeArtwork_4(
          this,
          Invocation.method(
            #getArtwork,
            [artworkId],
          ),
        )),
      ) as _i7.Future<_i4.Artwork>);
  @override
  _i7.Future<_i9.File?> downloadFeralfileArtwork(
    _i10.AssetToken? assetToken, {
    dynamic Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFeralfileArtwork,
          [assetToken],
          {#onReceiveProgress: onReceiveProgress},
        ),
        returnValue: _i7.Future<_i9.File?>.value(),
      ) as _i7.Future<_i9.File?>);
}
