// Mocks generated by Mockito 5.4.2 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_feral_file_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:autonomy_flutter/model/ff_account.dart' as _i3;
import 'package:autonomy_flutter/model/ff_exhibition.dart' as _i4;
import 'package:autonomy_flutter/model/ff_series.dart' as _i2;
import 'package:autonomy_flutter/model/otp.dart' as _i8;
import 'package:autonomy_flutter/screen/claim/claim_token_page.dart' as _i7;
import 'package:autonomy_flutter/service/feralfile_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFFSeries_0 extends _i1.SmartFake implements _i2.FFSeries {
  _FakeFFSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeralFileResaleInfo_1 extends _i1.SmartFake
    implements _i3.FeralFileResaleInfo {
  _FakeFeralFileResaleInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExhibition_2 extends _i1.SmartFake implements _i4.Exhibition {
  _FakeExhibition_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeralFileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeralFileService extends _i1.Mock implements _i5.FeralFileService {
  MockFeralFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.FFSeries> getAirdropSeriesFromExhibitionId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAirdropSeriesFromExhibitionId,
          [id],
        ),
        returnValue: _i6.Future<_i2.FFSeries>.value(_FakeFFSeries_0(
          this,
          Invocation.method(
            #getAirdropSeriesFromExhibitionId,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.FFSeries>);
  @override
  _i6.Future<_i2.FFSeries> getSeries(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSeries,
          [id],
        ),
        returnValue: _i6.Future<_i2.FFSeries>.value(_FakeFFSeries_0(
          this,
          Invocation.method(
            #getSeries,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.FFSeries>);
  @override
  _i6.Future<_i7.ClaimResponse?> claimToken({
    required String? seriesId,
    String? address,
    _i8.Otp? otp,
    _i6.Future<bool> Function(_i2.FFSeries)? onConfirm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimToken,
          [],
          {
            #seriesId: seriesId,
            #address: address,
            #otp: otp,
            #onConfirm: onConfirm,
          },
        ),
        returnValue: _i6.Future<_i7.ClaimResponse?>.value(),
      ) as _i6.Future<_i7.ClaimResponse?>);
  @override
  _i6.Future<_i4.Exhibition?> getExhibitionFromTokenID(String? artworkID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExhibitionFromTokenID,
          [artworkID],
        ),
        returnValue: _i6.Future<_i4.Exhibition?>.value(),
      ) as _i6.Future<_i4.Exhibition?>);
  @override
  _i6.Future<_i3.FeralFileResaleInfo> getResaleInfo(String? exhibitionID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResaleInfo,
          [exhibitionID],
        ),
        returnValue: _i6.Future<_i3.FeralFileResaleInfo>.value(
            _FakeFeralFileResaleInfo_1(
          this,
          Invocation.method(
            #getResaleInfo,
            [exhibitionID],
          ),
        )),
      ) as _i6.Future<_i3.FeralFileResaleInfo>);
  @override
  _i6.Future<String?> getPartnerFullName(String? exhibitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerFullName,
          [exhibitionId],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<_i4.Exhibition> getExhibition(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExhibition,
          [id],
        ),
        returnValue: _i6.Future<_i4.Exhibition>.value(_FakeExhibition_2(
          this,
          Invocation.method(
            #getExhibition,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.Exhibition>);
  @override
  _i6.Future<List<_i4.ExhibitionDetail>> getAllExhibitions({
    String? sortBy = r'openAt',
    String? sortOrder = r'DESC',
    int? limit = 8,
    int? offset = 0,
    bool? withArtworks = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExhibitions,
          [],
          {
            #sortBy: sortBy,
            #sortOrder: sortOrder,
            #limit: limit,
            #offset: offset,
            #withArtworks: withArtworks,
          },
        ),
        returnValue: _i6.Future<List<_i4.ExhibitionDetail>>.value(
            <_i4.ExhibitionDetail>[]),
      ) as _i6.Future<List<_i4.ExhibitionDetail>>);
  @override
  _i6.Future<_i4.Exhibition> getFeaturedExhibition() => (super.noSuchMethod(
        Invocation.method(
          #getFeaturedExhibition,
          [],
        ),
        returnValue: _i6.Future<_i4.Exhibition>.value(_FakeExhibition_2(
          this,
          Invocation.method(
            #getFeaturedExhibition,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Exhibition>);
  @override
  _i6.Future<List<_i3.Artwork>> getExhibitionArtworks(String? exhibitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExhibitionArtworks,
          [exhibitionId],
        ),
        returnValue: _i6.Future<List<_i3.Artwork>>.value(<_i3.Artwork>[]),
      ) as _i6.Future<List<_i3.Artwork>>);
  @override
  _i6.Future<List<_i3.Artwork>> getSeriesArtworks(String? seriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeriesArtworks,
          [seriesId],
        ),
        returnValue: _i6.Future<List<_i3.Artwork>>.value(<_i3.Artwork>[]),
      ) as _i6.Future<List<_i3.Artwork>>);
}
