// Mocks generated by Mockito 5.4.4 from annotations
// in autonomy_flutter/test/generate_mock/service/mock_configuration_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:autonomy_flutter/model/jwt.dart' as _i6;
import 'package:autonomy_flutter/model/network.dart' as _i7;
import 'package:autonomy_flutter/model/sent_artwork.dart' as _i8;
import 'package:autonomy_flutter/model/shared_postcard.dart' as _i10;
import 'package:autonomy_flutter/screen/chat/chat_thread_page.dart' as _i3;
import 'package:autonomy_flutter/screen/interactive_postcard/postcard_detail_page.dart'
    as _i12;
import 'package:autonomy_flutter/screen/interactive_postcard/stamp_preview.dart'
    as _i11;
import 'package:autonomy_flutter/service/configuration_service.dart' as _i4;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostcardChatConfig_1 extends _i1.SmartFake
    implements _i3.PostcardChatConfig {
  _FakePostcardChatConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigurationService extends _i1.Mock
    implements _i4.ConfigurationService {
  MockConfigurationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get showingNotification => (super.noSuchMethod(
        Invocation.getter(#showingNotification),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#showingNotification),
        ),
      ) as _i2.ValueNotifier<bool>);
  @override
  bool didMigrateToAccountSetting() => (super.noSuchMethod(
        Invocation.method(
          #didMigrateToAccountSetting,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setMigrateToAccountSetting(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMigrateToAccountSetting,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setDidShowLiveWithArt(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDidShowLiveWithArt,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool didShowLiveWithArt() => (super.noSuchMethod(
        Invocation.method(
          #didShowLiveWithArt,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setLastPullAnnouncementTime(int? lastPullTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastPullAnnouncementTime,
          [lastPullTime],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  int getLastPullAnnouncementTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastPullAnnouncementTime,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  _i5.Future<void> setRecordOwners(
    List<String>? owners, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRecordOwners,
          [owners],
          {#override: override},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<String> getRecordOwners() => (super.noSuchMethod(
        Invocation.method(
          #getRecordOwners,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i5.Future<void> setHasMerchandiseSupport(
    String? indexId, {
    bool? value = true,
    bool? isOverride = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHasMerchandiseSupport,
          [indexId],
          {
            #value: value,
            #isOverride: isOverride,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool hasMerchandiseSupport(String? indexId) => (super.noSuchMethod(
        Invocation.method(
          #hasMerchandiseSupport,
          [indexId],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setPostcardChatConfig(_i3.PostcardChatConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPostcardChatConfig,
          [config],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i3.PostcardChatConfig getPostcardChatConfig({
    required String? address,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostcardChatConfig,
          [],
          {
            #address: address,
            #id: id,
          },
        ),
        returnValue: _FakePostcardChatConfig_1(
          this,
          Invocation.method(
            #getPostcardChatConfig,
            [],
            {
              #address: address,
              #id: id,
            },
          ),
        ),
      ) as _i3.PostcardChatConfig);
  @override
  _i5.Future<void> setDidMigrateAddress(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDidMigrateAddress,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool getDidMigrateAddress() => (super.noSuchMethod(
        Invocation.method(
          #getDidMigrateAddress,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setAnnouncementLastPullTime(int? lastPullTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAnnouncementLastPullTime,
          [lastPullTime],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setOldUser() => (super.noSuchMethod(
        Invocation.method(
          #setOldUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool getIsOldUser() => (super.noSuchMethod(
        Invocation.method(
          #getIsOldUser,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setIAPReceipt(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPReceipt,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setIAPJWT(_i6.JWT? value) => (super.noSuchMethod(
        Invocation.method(
          #setIAPJWT,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setDevicePasscodeEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDevicePasscodeEnabled,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool isDevicePasscodeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDevicePasscodeEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setNotificationEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationEnabled,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool isNotificationEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isNotificationEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setAnalyticEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticEnabled,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setDoneOnboarding(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboarding,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool isDoneOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isDoneOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<dynamic> setLastTimeAskForSubscription(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastTimeAskForSubscription,
          [date],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  List<String> getTempStorageHiddenTokenIDs({_i7.Network? network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTempStorageHiddenTokenIDs,
          [],
          {#network: network},
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i5.Future<dynamic> updateTempStorageHiddenTokenIDs(
    List<String>? tokenIDs,
    bool? isAdd, {
    _i7.Network? network,
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTempStorageHiddenTokenIDs,
          [
            tokenIDs,
            isAdd,
          ],
          {
            #network: network,
            #override: override,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  List<_i8.SentArtwork> getRecentlySentToken() => (super.noSuchMethod(
        Invocation.method(
          #getRecentlySentToken,
          [],
        ),
        returnValue: <_i8.SentArtwork>[],
      ) as List<_i8.SentArtwork>);
  @override
  _i5.Future<dynamic> updateRecentlySentToken(
    List<_i8.SentArtwork>? sentArtwork, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecentlySentToken,
          [sentArtwork],
          {#override: override},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<void> setReadReleaseNotesInVersion(String? version) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadReleaseNotesInVersion,
          [version],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setPreviousBuildNumber(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setPreviousBuildNumber,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<String> getAccountHMACSecret() => (super.noSuchMethod(
        Invocation.method(
          #getAccountHMACSecret,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getAccountHMACSecret,
            [],
          ),
        )),
      ) as _i5.Future<String>);
  @override
  _i5.Future<void> setLastRemindReviewDate(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLastRemindReviewDate,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setCountOpenApp(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setCountOpenApp,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool showTokenDebugInfo() => (super.noSuchMethod(
        Invocation.method(
          #showTokenDebugInfo,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<dynamic> setShowTokenDebugInfo(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTokenDebugInfo,
          [show],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> setDoneOnboardingTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDoneOnboardingTime,
          [time],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> setSubscriptionTime(DateTime? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionTime,
          [time],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> setSentTezosArtworkMetric(int? hashedAddresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSentTezosArtworkMetric,
          [hashedAddresses],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<_i10.SharedPostcard> getSharedPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getSharedPostcard,
          [],
        ),
        returnValue: <_i10.SharedPostcard>[],
      ) as List<_i10.SharedPostcard>);
  @override
  _i5.Future<void> updateSharedPostcard(
    List<_i10.SharedPostcard>? sharedPostcards, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedPostcard,
          [sharedPostcards],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> removeSharedPostcardWhere(
          bool Function(_i10.SharedPostcard)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSharedPostcardWhere,
          [test],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<String> getListPostcardMint() => (super.noSuchMethod(
        Invocation.method(
          #getListPostcardMint,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i5.Future<void> setListPostcardMint(
    List<String>? tokenID, {
    bool? override = false,
    bool? isRemoved = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardMint,
          [tokenID],
          {
            #override: override,
            #isRemoved: isRemoved,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<_i11.StampingPostcard> getStampingPostcard() => (super.noSuchMethod(
        Invocation.method(
          #getStampingPostcard,
          [],
        ),
        returnValue: <_i11.StampingPostcard>[],
      ) as List<_i11.StampingPostcard>);
  @override
  _i5.Future<void> updateStampingPostcard(
    List<_i11.StampingPostcard>? values, {
    bool? override = false,
    bool? isRemove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStampingPostcard,
          [values],
          {
            #override: override,
            #isRemove: isRemove,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setProcessingStampPostcard(
    List<_i11.ProcessingStampPostcard>? values, {
    bool? override = false,
    bool? isRemove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setProcessingStampPostcard,
          [values],
          {
            #override: override,
            #isRemove: isRemove,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<_i11.ProcessingStampPostcard> getProcessingStampPostcard() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProcessingStampPostcard,
          [],
        ),
        returnValue: <_i11.ProcessingStampPostcard>[],
      ) as List<_i11.ProcessingStampPostcard>);
  @override
  _i5.Future<void> setAutoShowPostcard(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoShowPostcard,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool isAutoShowPostcard() => (super.noSuchMethod(
        Invocation.method(
          #isAutoShowPostcard,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<_i12.PostcardIdentity> getListPostcardAlreadyShowYouDidIt() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListPostcardAlreadyShowYouDidIt,
          [],
        ),
        returnValue: <_i12.PostcardIdentity>[],
      ) as List<_i12.PostcardIdentity>);
  @override
  _i5.Future<void> setListPostcardAlreadyShowYouDidIt(
    List<_i12.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListPostcardAlreadyShowYouDidIt,
          [value],
          {#override: override},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> setAlreadyShowPostcardUpdates(
    List<_i12.PostcardIdentity>? value, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAlreadyShowPostcardUpdates,
          [value],
          {#override: override},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<_i12.PostcardIdentity> getAlreadyShowPostcardUpdates() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlreadyShowPostcardUpdates,
          [],
        ),
        returnValue: <_i12.PostcardIdentity>[],
      ) as List<_i12.PostcardIdentity>);
  @override
  String getVersionInfo() => (super.noSuchMethod(
        Invocation.method(
          #getVersionInfo,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getVersionInfo,
            [],
          ),
        ),
      ) as String);
  @override
  _i5.Future<void> setVersionInfo(String? version) => (super.noSuchMethod(
        Invocation.method(
          #setVersionInfo,
          [version],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<String> getHiddenOrSentTokenIDs() => (super.noSuchMethod(
        Invocation.method(
          #getHiddenOrSentTokenIDs,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i5.Future<void> setShowPostcardBanner(bool? bool) => (super.noSuchMethod(
        Invocation.method(
          #setShowPostcardBanner,
          [bool],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool getShowPostcardBanner() => (super.noSuchMethod(
        Invocation.method(
          #getShowPostcardBanner,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setShowAddAddressBanner(bool? bool) => (super.noSuchMethod(
        Invocation.method(
          #setShowAddAddressBanner,
          [bool],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  bool getShowAddAddressBanner() => (super.noSuchMethod(
        Invocation.method(
          #getShowAddAddressBanner,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> setMerchandiseOrderIds(
    List<String>? ids, {
    bool? override = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMerchandiseOrderIds,
          [ids],
          {#override: override},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  List<String> getMerchandiseOrderIds() => (super.noSuchMethod(
        Invocation.method(
          #getMerchandiseOrderIds,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i5.Future<void> setReferralCode(String? referralCode) => (super.noSuchMethod(
        Invocation.method(
          #setReferralCode,
          [referralCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
