name: Deploy the Android app to Playstore internal track
on:
  workflow_dispatch:
    inputs:
      version:
        description: Build version (eg 0.30.0)
        required: true
      build-number:
        description: Build number
        required: true
      message:
        description: Change logs
        required: false
      testnet:
        type: boolean
        default: false
        required: false
        description: Using testnet (Default staging)
jobs:
  build:
    runs-on: [ self-hosted, macOS ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: stable

      - name: Set env
        run: |
          echo "FLUTTER_VERSION_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "FLUTTER_VERSION_CODE=${{ github.event.inputs.build-number }}" >> $GITHUB_ENV
          echo "BRANCH_KEY=${{ secrets.BRANCH_KEY }}" >> $GITHUB_ENV
          echo "BRANCH_KEY_TEST=${{ secrets.BRANCH_KEY_TEST }}" >> $GITHUB_ENV
          echo "SIGNATURE_HASH=${{ secrets.SIGNATURE_HASH }}" >> $GITHUB_ENV
          echo "SIGNATURE_HASH_INHOUSE=${{ secrets.SIGNATURE_HASH_INHOUSE }}" >> $GITHUB_ENV
          ${{ github.event.inputs.testnet == 'true' }} && echo APPCENTER_APP_ID=support-zzd0-28/Autonomy-Android-Test >> $GITHUB_ENV || echo APPCENTER_APP_ID=support-zzd0-28/Autonomy-Android-1 >> $GITHUB_ENV
          ${{ github.event.inputs.testnet == 'true' }} && echo NAME_SUFFIX=test-${{ github.event.inputs.build-number }} >> $GITHUB_ENV || echo NAME_SUFFIX=main-${{ github.event.inputs.build-number }} >> $GITHUB_ENV

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.KEY_VAULT_DEPLOYMENT_KEY }}
            ${{ secrets.SSH_ASSETS_KEY }}

      - name: Create env file
        run: |
          touch .env
          ${{ inputs.testnet == true }} && echo -e "${{ secrets.DEV_ENV_VARS }}" | sed 's/\\n/\n/g' >> .env || echo -e "${{ secrets.STAGING_ENV_VARS }}" | sed 's/\\n/\n/g' >> .env
          cat .env

      - name: Create env secret file
        run: |
          touch .env.secret
          ${{ inputs.testnet == true }} && echo -e "${{ secrets.DEV_ENV_SECRET }}" | sed 's/\\n/\n/g' >> .env.secret || echo -e "${{ secrets.STAGING_ENV_SECRET }}" | sed 's/\\n/\n/g' >> .env.secret
          cat .env.secret

      - name: Submodules update
        run: git -c submodule.auto-test.update=none submodule update --init --recursive
      - run: flutter pub cache repair
      - run: flutter pub get

      # Encrypt secrets before use
      - name: Encrypt Secrets
        run: |
          ./script/encrypt_secrets.sh ${{ secrets.ENTROPY }}

      - name: Clone the Key Vault
        run: |
          git clone git@github.com:bitmark-inc/mobile-signing-key-vault.git --depth 1
          cp mobile-signing-key-vault/android/bitmark-autonomy/release.keystore android/release.keystore
          cp mobile-signing-key-vault/android/bitmark-autonomy/release.properties android/key.properties

      - run: flutter build appbundle --flavor prd

      - name: Release notes
        run: |
          mkdir whatsnew
          echo "${{ github.event.inputs.message }}" > ./whatsnew/whatsnew-en-US

      # Upload APK to Google Play Internal Testing track
      - name: Upload APK to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.bitmark.autonomy_client
          releaseFiles: build/app/outputs/bundle/prdRelease/app-prd-release.aab
          track: qa
          mappingFile: build/app/outputs/mapping/prdRelease/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/prdRelease/out/lib
          whatsNewDirectory: ./whatsnew