name: Deployment

concurrency:
  group: internal-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
      - 'LICENSE.md'

jobs:
  fetch-deployment:
    runs-on: ubuntu-latest
    outputs:
      short_version: ${{ steps.extract-version.outputs.short_version }}
      build_number: ${{ steps.extract-version.outputs.build_number }}
      message: ${{ steps.pr-message.outputs.message }}
    steps:
      - name: Extract Short Version
        id: extract-version
        env:
            APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
        run: |
            # Make the API request and extract the short_version using jq
            API_RESPONSE=$(curl -X 'GET' \
            "https://api.appcenter.ms/v0.1/apps/support-zzd0-28/Autonomy-Android-Test/recent_releases" \
            -H 'accept: application/json' \
            -H "X-API-Token: $APPCENTER_API_TOKEN")

            BUILD_NUMBER=$(echo "$API_RESPONSE" | jq -r '.[0].version')
            # Increase the build number by 1
            ((BUILD_NUMBER++))
            
            SHORT_VERSION=$(echo "$API_RESPONSE" | jq -r '.[0].short_version')
            echo "short_version=$SHORT_VERSION" >> "$GITHUB_OUTPUT"
            echo "build_number=$BUILD_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Create PR Message
        id: pr-message
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          MESSAGE="Pull request: [${PR_TITLE}](${PR_URL})"
          echo "message=$MESSAGE" >> "$GITHUB_OUTPUT"

  deployment-ios:
    needs: fetch-deployment
    uses: ./.github/workflows/bmvn_build_appcenter_ios.yaml
    with:
      version: ${{ needs.fetch-deployment.outputs.short_version }}
      message: ${{ needs.fetch-deployment.outputs.message }}
      testnet: true
    secrets: inherit

  deployment-android:
    needs: fetch-deployment
    uses: ./.github/workflows/bmvn_build_appcenter_android.yaml
    with:
      version: ${{ needs.fetch-deployment.outputs.short_version }}
      message: ${{ needs.fetch-deployment.outputs.message }}
      build-number: ${{ needs.fetch-deployment.outputs.build_number }}
      testnet: true
    secrets: inherit